"""
Предобработка фрагментов документа.

Модули:
    segmentation    — выделение маски фрагмента (Otsu / Adaptive / GrabCut)
    contour         — извлечение и нормализация внешнего контура
    orientation     — оценка и коррекция угла поворота
    color_norm      — нормализация цвета (CLAHE, Gray World, гамма)
    denoise         — шумоподавление (Gaussian, Median, Bilateral, NLM, auto)
    augment         — аугментация данных (crop, rotate, noise, jitter, JPEG)
    edge_detector   — специализированное детектирование краёв (Canny, Sobel, LoG)
    skew_correction — коррекция наклона (Hough, projection, FFT)
    perspective     — коррекция перспективных искажений (contour, Hough)
    noise_reduction — расширенное шумоподавление (DenoiseResult, NLM, bilateral,
                      morphological, smart_denoise, batch_denoise)
    contrast        — улучшение контраста (ContrastResult, CLAHE, histeq,
                      gamma, stretch, retinex, auto_enhance, batch_enhance)
    binarizer       — бинаризация изображений (BinarizeResult, Otsu, Sauvola,
                      Niblack, Bernsen, adaptive, auto_binarize, batch_binarize)
    document_cleaner — очистка документов (тени, рамки, освещённость, пятна)
    noise_analyzer   — анализ шума (σ, SNR, JPEG-артефакты, зернистость, качество)
    fragment_cropper — обрезка к содержательной области (CropResult, auto_crop,
                       find_content_bbox, pad_image, crop_to_content, batch_crop)
    noise_reducer    — лёгкое шумоподавление (NoiseReductionResult, estimate_noise,
                       gaussian_reduce, median_reduce, bilateral_reduce, auto_reduce,
                       batch_reduce)
    deskewer         — коррекция наклона (DeskewResult, estimate_skew_projection,
                       estimate_skew_hough, deskew_image, auto_deskew, batch_deskew)
    background_remover — удаление фона (BackgroundRemovalResult, remove_background_thresh,
                         remove_background_edges, remove_background_grabcut,
                         auto_remove_background, batch_remove_background)
    patch_normalizer   — нормализация патчей (NormalizationParams, equalize_histogram,
                         stretch_contrast, standardize_patch, normalize_patch,
                         batch_normalize, compute_normalization_stats)
    quality_assessor        — оценка качества изображений (QualityReport, estimate_blur,
                              estimate_noise, estimate_contrast, estimate_completeness,
                              assess_quality, filter_by_quality, batch_assess_quality)
    illumination_corrector  — коррекция освещённости (IlluminationParams,
                              estimate_background, subtract_background,
                              correct_by_homomorph, correct_by_retinex,
                              correct_illumination, batch_correct, estimate_uniformity)
    morphology_ops          — морфологические операции (MorphParams, erode, dilate,
                              open_morph, close_morph, tophat, blackhat,
                              morphological_gradient, skeleton, remove_small_blobs,
                              fill_holes, apply_morph, batch_morph)
    frequency_filter        — фильтрация в частотной области (FrequencyFilterParams,
                              fft_image, ifft_image, gaussian_low_pass,
                              gaussian_high_pass, band_pass_filter, notch_filter,
                              apply_frequency_filter, batch_frequency_filter)
    channel_splitter        — разделение и обработка каналов (ChannelStats,
                              split_channels, merge_channels, channel_statistics,
                              equalize_channel, normalize_channel,
                              channel_difference, apply_per_channel, batch_split)
    adaptive_threshold      — адаптивная бинаризация (ThresholdParams,
                              global_threshold, adaptive_mean, adaptive_gaussian,
                              niblack_threshold, sauvola_threshold,
                              bernsen_threshold, apply_threshold, batch_threshold)
    noise_filter            — фильтрация шума (NoiseFilterParams, average_filter,
                              gaussian_filter, median_filter, bilateral_filter,
                              nlm_filter, apply_noise_filter, batch_noise_filter)
    edge_enhancer           — усиление краёв (EdgeEnhanceParams, unsharp_mask,
                              laplacian_enhance, hybrid_enhance,
                              gradient_scale_enhance, sharpness_measure,
                              apply_edge_enhance, batch_edge_enhance)
    color_normalizer        — нормализация цвета (NormConfig, NormResult,
                              gamma_correction, equalize_histogram, apply_clahe,
                              grey_world_balance, max_rgb_balance, minmax_normalize,
                              normalize_image, batch_normalize)
    image_enhancer          — улучшение качества изображений (EnhanceConfig,
                              EnhanceResult, sharpen_image, denoise_image,
                              enhance_contrast, enhance_image, batch_enhance)
    gradient_analyzer       — анализ градиентов (GradientConfig, GradientMap,
                              GradientProfile, compute_gradient_map,
                              compute_orientation_histogram,
                              extract_gradient_profile, compare_gradient_profiles,
                              batch_extract_gradient_profiles)
    patch_sampler           — выборка патчей (SampleConfig, PatchSample,
                              SampleResult, sample_grid_patches,
                              sample_random_patches, sample_border_patches,
                              sample_stride_patches, sample_patches,
                              extract_patch_images, batch_sample_patches)
    frequency_analyzer      — частотный анализ (FreqConfig, FreqSpectrum,
                              FreqDescriptor, compute_power_spectrum,
                              compute_band_energies, compute_spectral_centroid,
                              compute_spectral_entropy, extract_top_frequencies,
                              extract_freq_descriptor, compare_freq_descriptors,
                              batch_extract_freq_descriptors)
    warp_corrector          — коррекция аффинных искажений (WarpConfig,
                              WarpEstimate, WarpResult, estimate_warp,
                              apply_warp, correct_warp, warp_score,
                              batch_correct_warp)
    contrast_enhancer       — улучшение контрастности (EnhanceConfig,
                              EnhanceResult, equalize_histogram,
                              stretch_contrast, apply_gamma, clahe_enhance,
                              enhance_contrast, batch_enhance)
    contour_processor       — обработка контуров фрагментов (ContourConfig,
                              ContourStats, ContourResult, resample_contour,
                              smooth_contour, rdp_simplify, normalize_contour,
                              contour_area, contour_perimeter,
                              compute_contour_stats, process_contour,
                              batch_process_contours)
    illumination_normalizer — нормализация освещения (IllumConfig,
                              IllumResult, estimate_illumination,
                              subtract_background, normalize_mean_std,
                              apply_clahe, normalize_illumination,
                              batch_normalize_illumination)
    edge_sharpener          — повышение резкости краёв (SharpenerConfig,
                              SharpenerResult, unsharp_mask, laplacian_sharpen,
                              high_pass_sharpen, sharpen_image, sharpen_edges,
                              batch_sharpen)
"""
from .segmentation import segment_fragment
from .contour import extract_contour
from .orientation import estimate_orientation, rotate_to_upright
from .color_norm import (
    normalize_color,
    clahe_normalize,
    white_balance,
    gamma_correction,
    normalize_brightness,
    batch_normalize,
)
from .denoise import (
    gaussian_denoise,
    median_denoise,
    bilateral_denoise,
    nlmeans_denoise,
    auto_denoise,
    denoise_batch,
)
from .augment import (
    random_crop,
    random_rotate,
    add_gaussian_noise,
    add_salt_pepper,
    brightness_jitter,
    simulate_scan_noise,
    jpeg_compress,
    augment_batch,
)
from .edge_detector import (
    detect_edges,
    adaptive_canny,
    sobel_edges,
    laplacian_edges,
    refine_edge_contour,
    edge_density,
    edge_orientation_hist,
    EdgeDetectionResult,
)
from .skew_correction import (
    SkewResult,
    detect_skew_hough,
    detect_skew_projection,
    detect_skew_fft,
    correct_skew,
    auto_correct_skew,
    skew_confidence,
    batch_correct_skew,
)
from .perspective import (
    PerspectiveResult,
    order_corners,
    four_point_transform,
    detect_corners_contour,
    detect_corners_hough,
    correct_perspective,
    auto_correct_perspective,
    batch_correct_perspective,
)
from .noise_reduction import (
    DenoiseResult,
    estimate_noise_level,
    denoise_gaussian,
    denoise_median,
    denoise_nlm,
    denoise_bilateral,
    denoise_morphological,
    smart_denoise,
    batch_denoise,
)
from .contrast import (
    ContrastResult,
    measure_contrast,
    enhance_clahe,
    enhance_histeq,
    enhance_gamma,
    enhance_stretch,
    enhance_retinex,
    auto_enhance,
    batch_enhance,
)
from .binarizer import (
    BinarizeResult,
    binarize_otsu,
    binarize_adaptive,
    binarize_sauvola,
    binarize_niblack,
    binarize_bernsen,
    auto_binarize,
    batch_binarize,
)
from .document_cleaner import (
    CleanResult,
    remove_shadow,
    remove_border_artifacts,
    normalize_illumination,
    remove_blobs,
    auto_clean,
    batch_clean,
)
from .noise_analyzer import (
    NoiseAnalysisResult,
    estimate_noise_sigma,
    estimate_snr,
    detect_jpeg_artifacts,
    estimate_grain,
    analyze_noise,
    batch_analyze_noise,
)
from .fragment_cropper import (
    CropResult,
    find_content_bbox,
    pad_image,
    crop_to_content,
    auto_crop,
    batch_crop,
)
from .noise_reducer import (
    NoiseReductionResult,
    estimate_noise,
    gaussian_reduce,
    median_reduce,
    bilateral_reduce,
    auto_reduce,
    batch_reduce,
)
from .deskewer import (
    DeskewResult,
    estimate_skew_projection,
    estimate_skew_hough,
    deskew_image,
    auto_deskew,
    batch_deskew,
)
from .background_remover import (
    BackgroundRemovalResult,
    remove_background_thresh,
    remove_background_edges,
    remove_background_grabcut,
    auto_remove_background,
    batch_remove_background,
)
from .patch_normalizer import (
    NormalizationParams,
    equalize_histogram,
    stretch_contrast,
    standardize_patch,
    normalize_patch,
    batch_normalize as batch_normalize_patches,
    compute_normalization_stats,
)
from .quality_assessor import (
    QualityReport,
    estimate_blur,
    estimate_noise,
    estimate_contrast,
    estimate_completeness,
    assess_quality,
    filter_by_quality,
    batch_assess_quality,
)
from .illumination_corrector import (
    IlluminationParams,
    estimate_background,
    subtract_background,
    correct_by_homomorph,
    correct_by_retinex,
    correct_illumination,
    batch_correct,
    estimate_uniformity,
)
from .morphology_ops import (
    MorphParams,
    erode,
    dilate,
    open_morph,
    close_morph,
    tophat,
    blackhat,
    morphological_gradient,
    skeleton,
    remove_small_blobs,
    fill_holes,
    apply_morph,
    batch_morph,
)
from .frequency_filter import (
    FrequencyFilterParams,
    fft_image,
    ifft_image,
    gaussian_low_pass,
    gaussian_high_pass,
    band_pass_filter,
    notch_filter,
    apply_frequency_filter,
    batch_frequency_filter,
)
from .channel_splitter import (
    ChannelStats,
    split_channels,
    merge_channels,
    channel_statistics,
    equalize_channel,
    normalize_channel,
    channel_difference,
    apply_per_channel,
    batch_split,
)
from .adaptive_threshold import (
    ThresholdParams,
    global_threshold,
    adaptive_mean,
    adaptive_gaussian,
    niblack_threshold,
    sauvola_threshold,
    bernsen_threshold,
    apply_threshold,
    batch_threshold,
)
from .noise_filter import (
    NoiseFilterParams,
    average_filter,
    gaussian_filter,
    median_filter,
    bilateral_filter,
    nlm_filter,
    apply_noise_filter,
    batch_noise_filter,
)
from .edge_enhancer import (
    EdgeEnhanceParams,
    unsharp_mask,
    laplacian_enhance,
    hybrid_enhance,
    gradient_scale_enhance,
    sharpness_measure,
    apply_edge_enhance,
    batch_edge_enhance,
)
from .color_normalizer import (
    NormConfig,
    NormResult,
    gamma_correction as gamma_correction_new,
    equalize_histogram as equalize_histogram_new,
    apply_clahe,
    grey_world_balance,
    max_rgb_balance,
    minmax_normalize,
    normalize_image,
    batch_normalize as batch_normalize_color,
)
from .image_enhancer import (
    EnhanceConfig,
    EnhanceResult,
    sharpen_image,
    denoise_image,
    enhance_contrast,
    enhance_image,
    batch_enhance as batch_enhance_images,
)
from .gradient_analyzer import (
    GradientConfig,
    GradientMap,
    GradientProfile,
    compute_gradient_map,
    compute_orientation_histogram,
    extract_gradient_profile,
    compare_gradient_profiles,
    batch_extract_gradient_profiles,
)
from .patch_sampler import (
    SampleConfig,
    PatchSample,
    SampleResult,
    sample_grid_patches,
    sample_random_patches,
    sample_border_patches,
    sample_stride_patches,
    sample_patches,
    extract_patch_images,
    batch_sample_patches,
)
from .frequency_analyzer import (
    FreqConfig,
    FreqSpectrum,
    FreqDescriptor,
    compute_power_spectrum,
    compute_band_energies,
    compute_spectral_centroid,
    compute_spectral_entropy,
    extract_top_frequencies,
    extract_freq_descriptor,
    compare_freq_descriptors,
    batch_extract_freq_descriptors,
)
from .warp_corrector import (
    WarpConfig,
    WarpEstimate,
    WarpResult,
    estimate_warp,
    apply_warp,
    correct_warp,
    warp_score,
    batch_correct_warp,
)
from .contrast_enhancer import (
    EnhanceConfig,
    EnhanceResult,
    equalize_histogram,
    stretch_contrast,
    apply_gamma,
    clahe_enhance,
    enhance_contrast,
    batch_enhance,
)
from .contour_processor import (
    ContourConfig,
    ContourStats,
    ContourResult,
    resample_contour,
    smooth_contour,
    rdp_simplify,
    normalize_contour,
    contour_area,
    contour_perimeter,
    compute_contour_stats,
    process_contour,
    batch_process_contours,
)
from .illumination_normalizer import (
    IllumConfig,
    IllumResult,
    estimate_illumination,
    subtract_background,
    normalize_mean_std,
    apply_clahe,
    normalize_illumination,
    batch_normalize_illumination,
)
from .edge_sharpener import (
    SharpenerConfig,
    SharpenerResult,
    unsharp_mask as edge_unsharp_mask,
    laplacian_sharpen,
    high_pass_sharpen,
    sharpen_image as edge_sharpen_image,
    sharpen_edges,
    batch_sharpen,
)

__all__ = [
    "segment_fragment",
    "extract_contour",
    "estimate_orientation",
    "rotate_to_upright",
    "normalize_color",
    "clahe_normalize",
    "white_balance",
    "gamma_correction",
    "normalize_brightness",
    "batch_normalize",
    "gaussian_denoise",
    "median_denoise",
    "bilateral_denoise",
    "nlmeans_denoise",
    "auto_denoise",
    "denoise_batch",
    "random_crop",
    "random_rotate",
    "add_gaussian_noise",
    "add_salt_pepper",
    "brightness_jitter",
    "simulate_scan_noise",
    "jpeg_compress",
    "augment_batch",
    "detect_edges",
    "adaptive_canny",
    "sobel_edges",
    "laplacian_edges",
    "refine_edge_contour",
    "edge_density",
    "edge_orientation_hist",
    "EdgeDetectionResult",
    "SkewResult",
    "detect_skew_hough",
    "detect_skew_projection",
    "detect_skew_fft",
    "correct_skew",
    "auto_correct_skew",
    "skew_confidence",
    "batch_correct_skew",
    "PerspectiveResult",
    "order_corners",
    "four_point_transform",
    "detect_corners_contour",
    "detect_corners_hough",
    "correct_perspective",
    "auto_correct_perspective",
    "batch_correct_perspective",
    # Расширенное шумоподавление
    "DenoiseResult",
    "estimate_noise_level",
    "denoise_gaussian",
    "denoise_median",
    "denoise_nlm",
    "denoise_bilateral",
    "denoise_morphological",
    "smart_denoise",
    "batch_denoise",
    # Улучшение контраста
    "ContrastResult",
    "measure_contrast",
    "enhance_clahe",
    "enhance_histeq",
    "enhance_gamma",
    "enhance_stretch",
    "enhance_retinex",
    "auto_enhance",
    "batch_enhance",
    # Бинаризация
    "BinarizeResult",
    "binarize_otsu",
    "binarize_adaptive",
    "binarize_sauvola",
    "binarize_niblack",
    "binarize_bernsen",
    "auto_binarize",
    "batch_binarize",
    # Очистка документов
    "CleanResult",
    "remove_shadow",
    "remove_border_artifacts",
    "normalize_illumination",
    "remove_blobs",
    "auto_clean",
    "batch_clean",
    # Анализ шума
    "NoiseAnalysisResult",
    "estimate_noise_sigma",
    "estimate_snr",
    "detect_jpeg_artifacts",
    "estimate_grain",
    "analyze_noise",
    "batch_analyze_noise",
    # Обрезка фрагментов
    "CropResult",
    "find_content_bbox",
    "pad_image",
    "crop_to_content",
    "auto_crop",
    "batch_crop",
    # Лёгкое шумоподавление
    "NoiseReductionResult",
    "estimate_noise",
    "gaussian_reduce",
    "median_reduce",
    "bilateral_reduce",
    "auto_reduce",
    "batch_reduce",
    # Коррекция наклона
    "DeskewResult",
    "estimate_skew_projection",
    "estimate_skew_hough",
    "deskew_image",
    "auto_deskew",
    "batch_deskew",
    # Удаление фона
    "BackgroundRemovalResult",
    "remove_background_thresh",
    "remove_background_edges",
    "remove_background_grabcut",
    "auto_remove_background",
    "batch_remove_background",
    # Нормализация патчей
    "NormalizationParams",
    "equalize_histogram",
    "stretch_contrast",
    "standardize_patch",
    "normalize_patch",
    "batch_normalize_patches",
    "compute_normalization_stats",
    # Оценка качества изображений
    "QualityReport",
    "estimate_blur",
    "estimate_noise",
    "estimate_contrast",
    "estimate_completeness",
    "assess_quality",
    "filter_by_quality",
    "batch_assess_quality",
    # Коррекция освещённости
    "IlluminationParams",
    "estimate_background",
    "subtract_background",
    "correct_by_homomorph",
    "correct_by_retinex",
    "correct_illumination",
    "batch_correct",
    "estimate_uniformity",
    # Морфологические операции
    "MorphParams",
    "erode",
    "dilate",
    "open_morph",
    "close_morph",
    "tophat",
    "blackhat",
    "morphological_gradient",
    "skeleton",
    "remove_small_blobs",
    "fill_holes",
    "apply_morph",
    "batch_morph",
    # Фильтрация в частотной области
    "FrequencyFilterParams",
    "fft_image",
    "ifft_image",
    "gaussian_low_pass",
    "gaussian_high_pass",
    "band_pass_filter",
    "notch_filter",
    "apply_frequency_filter",
    "batch_frequency_filter",
    # Разделение и обработка каналов
    "ChannelStats",
    "split_channels",
    "merge_channels",
    "channel_statistics",
    "equalize_channel",
    "normalize_channel",
    "channel_difference",
    "apply_per_channel",
    "batch_split",
    # Адаптивная бинаризация
    "ThresholdParams",
    "global_threshold",
    "adaptive_mean",
    "adaptive_gaussian",
    "niblack_threshold",
    "sauvola_threshold",
    "bernsen_threshold",
    "apply_threshold",
    "batch_threshold",
    # Фильтрация шума
    "NoiseFilterParams",
    "average_filter",
    "gaussian_filter",
    "median_filter",
    "bilateral_filter",
    "nlm_filter",
    "apply_noise_filter",
    "batch_noise_filter",
    # Усиление краёв
    "EdgeEnhanceParams",
    "unsharp_mask",
    "laplacian_enhance",
    "hybrid_enhance",
    "gradient_scale_enhance",
    "sharpness_measure",
    "apply_edge_enhance",
    "batch_edge_enhance",
    # Нормализация цвета
    "NormConfig",
    "NormResult",
    "gamma_correction_new",
    "equalize_histogram_new",
    "apply_clahe",
    "grey_world_balance",
    "max_rgb_balance",
    "minmax_normalize",
    "normalize_image",
    "batch_normalize_color",
    # Улучшение качества изображений
    "EnhanceConfig",
    "EnhanceResult",
    "sharpen_image",
    "denoise_image",
    "enhance_contrast",
    "enhance_image",
    "batch_enhance_images",
    # Анализ градиентов
    "GradientConfig",
    "GradientMap",
    "GradientProfile",
    "compute_gradient_map",
    "compute_orientation_histogram",
    "extract_gradient_profile",
    "compare_gradient_profiles",
    "batch_extract_gradient_profiles",
    # Выборка патчей
    "SampleConfig",
    "PatchSample",
    "SampleResult",
    "sample_grid_patches",
    "sample_random_patches",
    "sample_border_patches",
    "sample_stride_patches",
    "sample_patches",
    "extract_patch_images",
    "batch_sample_patches",
    # Частотный анализ
    "FreqConfig",
    "FreqSpectrum",
    "FreqDescriptor",
    "compute_power_spectrum",
    "compute_band_energies",
    "compute_spectral_centroid",
    "compute_spectral_entropy",
    "extract_top_frequencies",
    "extract_freq_descriptor",
    "compare_freq_descriptors",
    "batch_extract_freq_descriptors",
    # Коррекция перспективных и аффинных искажений
    "WarpConfig",
    "WarpEstimate",
    "WarpResult",
    "estimate_warp",
    "apply_warp",
    "correct_warp",
    "warp_score",
    "batch_correct_warp",
    # Улучшение контрастности
    "EnhanceConfig",
    "EnhanceResult",
    "equalize_histogram",
    "stretch_contrast",
    "apply_gamma",
    "clahe_enhance",
    "enhance_contrast",
    "batch_enhance",
    # Обработка контуров фрагментов
    "ContourConfig",
    "ContourStats",
    "ContourResult",
    "resample_contour",
    "smooth_contour",
    "rdp_simplify",
    "normalize_contour",
    "contour_area",
    "contour_perimeter",
    "compute_contour_stats",
    "process_contour",
    "batch_process_contours",
    # Нормализация освещения
    "IllumConfig",
    "IllumResult",
    "estimate_illumination",
    "subtract_background",
    "normalize_mean_std",
    "apply_clahe",
    "normalize_illumination",
    "batch_normalize_illumination",
    # Повышение резкости краёв
    "SharpenerConfig",
    "SharpenerResult",
    "edge_unsharp_mask",
    "laplacian_sharpen",
    "high_pass_sharpen",
    "edge_sharpen_image",
    "sharpen_edges",
    "batch_sharpen",
]
