"""
Утилиты: логирование, геометрия, кэш дескрипторов, ввод-вывод.

Модули:
    logger     — структурированное логирование с цветами (get_logger, stage, PipelineTimer)
    geometry   — геометрические операции (rotation_matrix_2d, polygon_area, poly_iou, …)
    cache      — LRU-кэш и дисковый кэш дескрипторов (DescriptorCache, DiskCache, @cached)
    io         — загрузка/сохранение фрагментов и Assembly (load_image_dir, save_assembly_json, …)
    profiler   — профилировщик шагов пайплайна (StepProfile, PipelineProfiler, @timed)
    visualizer — утилиты визуализации (word boxes, contours, matches, confidence bar)
    metrics    — метрики качества восстановления (ReconstructionMetrics, IoU, Kendall τ,
                 permutation distance, precision/recall, placement accuracy)
    image_stats    — статистический анализ изображений (ImageStats, энтропия, резкость,
                     гистограммные моменты, градиентные статистики, compare_images)
    patch_extractor — извлечение патчей (Patch, PatchSet, grid, sliding, random, border)
    image_io        — загрузка/сохранение (ImageRecord, load_image, save_image,
                      load_directory, filter_by_extension, parse_fragment_id,
                      resize_to_max, batch_resize)
    transform_utils — геометрические преобразования (rotate, flip, scale, crop_region,
                      affine_from_params, compose_affines, apply_affine,
                      apply_homography, batch_rotate)
    color_utils     — цветовые утилиты (to_gray, to_lab, to_hsv, from_lab,
                      compute_histogram, compare_histograms, dominant_colors,
                      color_distance, strip_histogram)
    mask_utils      — утилиты масок (create_alpha_mask, apply_mask, erode_mask,
                      dilate_mask, mask_from_contour, combine_masks,
                      crop_to_mask, invert_mask)
    array_utils     — утилиты numpy-массивов (normalize_array, pad_to_shape,
                      crop_center, stack_arrays, chunk_array, sliding_window,
                      flatten_images, unflatten_images, compute_pairwise_norms)
    contour_utils   — утилиты контуров (simplify_contour, interpolate_contour,
                      contour_area, contour_perimeter, contour_bbox,
                      contour_centroid, contour_iou, align_contour_orientation,
                      contours_to_mask, mask_to_contour)
    histogram_utils — утилиты гистограмм (compute_1d_histogram, compute_2d_histogram,
                      histogram_equalization, histogram_specification,
                      earth_mover_distance, chi_squared_distance,
                      histogram_intersection, backproject, joint_histogram)
    keypoint_utils  — ключевые точки и дескрипторы (KeypointSet, detect_keypoints,
                      filter_by_response, filter_by_region, describe_keypoints,
                      match_descriptors, filter_matches_ransac, keypoints_to_array,
                      array_to_keypoints, compute_match_score)
    signal_utils    — 1D обработка сигналов (smooth_signal, normalize_signal,
                      find_peaks, find_valleys, compute_autocorrelation,
                      compute_cross_correlation, signal_energy, segment_signal,
                      resample_signal, phase_shift)
    bbox_utils      — утилиты ограничивающих прямоугольников (BBox, bbox_iou,
                      bbox_intersection, bbox_union, expand_bbox, crop_image,
                      bboxes_from_mask, merge_overlapping_bboxes,
                      bbox_center, bbox_aspect_ratio)
    sparse_utils    — утилиты разреженных матриц оценок (SparseEntry,
                      to_sparse_entries, from_sparse_entries, sparse_top_k,
                      threshold_matrix, symmetrize_matrix, normalize_matrix,
                      diagonal_zeros, matrix_sparsity, top_k_per_row)
    clustering_utils — кластеризация фрагментов (ClusterResult, kmeans_cluster,
                       assign_to_clusters, compute_inertia, silhouette_score_approx,
                       hierarchical_cluster, find_optimal_k, cluster_indices,
                       merge_clusters)
    distance_utils  — метрики расстояния и сходства (euclidean_distance,
                      cosine_distance, cosine_similarity, manhattan_distance,
                      chebyshev_distance, hausdorff_distance, chamfer_distance,
                      normalized_distance, pairwise_distances, nearest_neighbor_dist)
    smoothing_utils — сглаживание сигналов и контуров (SmoothingParams,
                      moving_average, gaussian_smooth, median_smooth,
                      exponential_smooth, savgol_smooth, smooth_contour,
                      apply_smoothing, batch_smooth)
    feature_selector — выбор признаков (FeatureSet, SelectionResult,
                       variance_selection, correlation_selection, rank_features,
                       pca_reduce, normalize_features, select_top_k,
                       apply_selection, batch_select)
    graph_utils      — граф совместимости фрагментов (GraphEdge, FragmentGraph,
                       build_graph, dijkstra, shortest_path, minimum_spanning_tree,
                       connected_components, node_degrees, subgraph, batch_build_graphs)
    cache_manager    — LRU-кэш промежуточных результатов (CacheEntry, CacheStats,
                       LRUCache, make_cache, cached_call, merge_caches)
    progress_tracker — трекер прогресса пайплайна (StepRecord, PipelineReport,
                       ProgressTracker, make_tracker, run_step, summarize_tracker)
    config_manager   — управление конфигурацией (ConfigField, ConfigSpec,
                       ConfigSnapshot, validate_field_type, validate_config,
                       load_config, merge_configs, diff_configs,
                       make_config_snapshot, batch_validate)
    result_cache     — кэш промежуточных результатов с TTL (CachePolicy, CacheRecord,
                       CacheSummary, ResultCache, make_cache, cached_result,
                       merge_caches, evict_expired)
    metric_tracker   — отслеживание метрик (MetricRecord, MetricStats, TrackerConfig,
                       MetricTracker, make_tracker, merge_trackers,
                       compute_moving_average, export_metrics)
    event_log        — журнал событий пайплайна (EventLogConfig, EventRecord,
                       EventSummary, EventLog, make_event_log, log_event,
                       filter_events, summarize_events, merge_event_logs,
                       export_event_log)
    batch_processor  — пакетная обработка элементов (ProcessConfig, ProcessItem,
                       BatchSummary, make_processor, process_items,
                       filter_successful, retry_failed_items, split_batch,
                       merge_batch_results)
    event_bus        — шина событий pub/sub (BusConfig, EventRecord, BusSummary,
                       EventBus, make_event_bus, collect_events, drain_bus)
    pipeline_runner  — запуск многоэтапного пайплайна (RunnerConfig, StepResult,
                       PipelineResult, PipelineStep, make_step, run_pipeline,
                       get_step_output, filter_step_results, retry_failed_steps)
    polygon_utils    — геометрия полигонов (polygon_area, polygon_perimeter,
                       polygon_centroid, point_in_polygon, convex_hull,
                       polygon_bounding_box, polygon_aspect_ratio,
                       translate_polygon, scale_polygon, rotate_polygon,
                       polygon_similarity)
    score_aggregator — агрегация оценок совместимости (AggregationMethod,
                       ScoreVector, AggregationResult, weighted_sum,
                       harmonic_mean, geometric_mean, aggregate_pair,
                       aggregate_matrix, top_k_pairs, batch_aggregate)
    tile_utils       — разбивка изображений на тайлы (TileConfig, Tile,
                       tile_image, reassemble_tiles, tile_overlap_ratio,
                       filter_tiles_by_content, compute_tile_grid,
                       batch_tile_images)
    contour_sampler  — дискретизация контуров (SamplerConfig, SampledContour,
                       sample_uniform, sample_curvature, sample_random,
                       sample_corners, sample_contour, normalize_contour,
                       batch_sample)
    morph_utils      — морфологическая обработка (MorphConfig,
                       apply_erosion, apply_dilation, apply_opening, apply_closing,
                       get_skeleton, label_regions, filter_regions_by_size,
                       compute_region_stats, batch_morphology)
    voting_utils     — голосование и консенсус (VoteConfig,
                       cast_pair_votes, aggregate_pair_votes, cast_position_votes,
                       majority_vote, weighted_vote, rank_fusion, batch_vote)
    patch_utils      — извлечение и сравнение патчей (PatchConfig,
                       extract_patch, extract_patches, normalize_patch,
                       compare_patches, patch_ssd, patch_ncc, patch_mse,
                       batch_compare)
    text_utils       — анализ и очистка текста (TextConfig, TextBlock,
                       clean_ocr_text, estimate_text_density, find_text_lines,
                       segment_words, compute_text_score, compare_text_blocks,
                       align_text_blocks, batch_clean_text)
    gradient_utils   — градиентный анализ изображений (GradientConfig,
                       compute_gradient_magnitude, compute_gradient_direction,
                       compute_sobel, compute_laplacian, threshold_gradient,
                       suppress_non_maximum, compute_edge_density,
                       batch_compute_gradients)
    sequence_utils   — операции над последовательностями (SequenceConfig,
                       rank_sequence, normalize_sequence, invert_sequence,
                       sliding_scores, align_sequences, kendall_tau_distance,
                       longest_increasing, segment_by_threshold, batch_rank)
    topology_utils   — топологические утилиты (TopologyConfig,
                       compute_euler_number, count_holes, compute_solidity,
                       compute_extent, compute_convexity, compute_compactness,
                       is_simply_connected, shape_complexity, batch_topology)
    curvature_utils  — утилиты кривизны контуров (CurvatureConfig,
                       compute_curvature, compute_total_curvature,
                       find_inflection_points, compute_turning_angle,
                       smooth_curvature, corner_score, find_corners,
                       batch_curvature)
    window_utils     — оконная обработка сигналов (WindowConfig,
                       apply_window_function, rolling_mean, rolling_std,
                       rolling_max, rolling_min, compute_overlap,
                       split_into_windows, merge_windows, batch_rolling)
    stats_utils      — статистические утилиты (StatsConfig,
                       describe, zscore_array, iqr, winsorize,
                       percentile_rank, outlier_mask, running_stats,
                       weighted_mean, weighted_std, batch_describe)
    threshold_utils  — пороговая обработка (ThresholdConfig,
                       apply_threshold, binarize, adaptive_threshold,
                       soft_threshold, threshold_matrix,
                       hysteresis_threshold, otsu_threshold,
                       count_above, fraction_above, batch_threshold)
    interpolation_utils — интерполяция сигналов и оценок (InterpolationConfig,
                          lerp, lerp_array, bilinear_interpolate, resample_1d,
                          fill_missing, interpolate_scores,
                          smooth_interpolate, batch_resample)
    sampling_utils      — случайная выборка для оптимизации (SamplingConfig,
                          uniform_sample, sample_angle, sample_position,
                          sample_positions_grid, sample_permutation,
                          weighted_sample, acceptance_probability,
                          sample_swap_pair, batch_uniform_sample)
    annealing_schedule  — температурные расписания для SA (ScheduleConfig,
                          TemperatureRecord, linear_schedule,
                          geometric_schedule, exponential_schedule,
                          cosine_schedule, stepped_schedule,
                          get_temperature, estimate_steps,
                          batch_temperatures)
    edge_scorer         — оценка совместимости краёв (EdgeScoreConfig,
                          EdgeScoreResult, score_edge_overlap,
                          score_edge_curvature, score_edge_length,
                          score_edge_endpoints, aggregate_edge_scores,
                          rank_edge_pairs, batch_score_edges)
    alignment_utils     — выравнивание и регистрация кривых (AlignmentConfig,
                          AlignmentResult, normalize_for_alignment,
                          find_best_rotation, find_best_translation,
                          compute_alignment_error, align_curves_procrustes,
                          align_curves_icp, alignment_score,
                          batch_align_curves)
    curve_metrics       — метрики сравнения кривых (CurveMetricConfig,
                          CurveComparisonResult, curve_l2, curve_l2_mirror,
                          hausdorff_distance, frechet_distance_approx,
                          curve_length, length_ratio,
                          compare_curves, batch_compare_curves)
    segment_utils       — анализ сегментов маски (SegmentConfig, RegionInfo,
                          label_mask, region_info, all_regions,
                          filter_regions, largest_region, mask_from_labels,
                          mask_statistics, mask_bounding_box, extract_boundary)
    polygon_ops_utils   — операции над полигонами (PolygonOpsConfig,
                          PolygonOverlapResult, PolygonStats,
                          signed_area, polygon_area, polygon_perimeter,
                          polygon_centroid, polygon_bounding_box,
                          polygon_stats, point_in_polygon, polygon_overlap,
                          remove_collinear, ensure_ccw, ensure_cw,
                          polygon_similarity, batch_polygon_stats,
                          batch_polygon_overlap)
    score_matrix_utils  — утилиты матриц оценок (ScoreMatrixConfig,
                          MatrixStats, RankEntry,
                          zero_diagonal, symmetrize, threshold_matrix,
                          normalize_rows, top_k_indices,
                          matrix_stats, top_k_per_row,
                          filter_by_threshold, intra_fragment_mask,
                          apply_intra_fragment_mask, batch_matrix_stats)
    image_transform_utils — геометрические преобразования изображений
                          (ImageTransformConfig, TransformResult,
                           rotate_image, flip_horizontal, flip_vertical,
                           pad_image, crop_image, resize_image,
                           resize_to_max_side, apply_affine,
                           rotation_matrix_2x3, batch_rotate,
                           batch_pad, batch_resize_to_max)
    rotation_utils      — утилиты поворота (RotationConfig,
                          rotate_image_angle, rotate_points_angle,
                          normalize_angle, angle_difference,
                          nearest_discrete, angles_to_matrix,
                          batch_rotate_images, estimate_rotation)
    icp_utils           — утилиты ICP-выравнивания (ICPConfig,
                          centroid, center_points, scale_points,
                          resample_uniform, nearest_neighbours,
                          filter_correspondences, svd_rotation,
                          svd_translation, compute_rmse,
                          rmse_after_transform, has_converged,
                          compose_transforms, invert_transform,
                          PairAlignResult, batch_nearest_neighbours,
                          transform_points, align_to_first)
    descriptor_utils    — утилиты дескрипторов (DescriptorConfig,
                          l2_normalize, l1_normalize, batch_l2_normalize,
                          l2_distance, cosine_distance, chi2_distance,
                          l1_distance, descriptor_distance,
                          pairwise_l2, pairwise_cosine,
                          DescriptorMatch, nn_match, ratio_test,
                          mean_pool, max_pool, vlad_encode,
                          batch_nn_match, top_k_matches,
                          filter_matches_by_distance)
    render_utils        — утилиты рендеринга (CanvasConfig, MosaicConfig,
                          rotation_matrix_2d, bounding_box_of_rotated,
                          compute_canvas_size, make_blank_canvas,
                          resize_keep_aspect, pad_to_square, make_thumbnail,
                          paste_with_mask, compute_grid_layout, make_mosaic,
                          save_image, horizontal_concat)
    tracker_utils       — утилиты отслеживания итерационного прогресса
                          (TrackerConfig, StepRecord, IterTracker,
                          create_iter_tracker, record_step, get_values,
                          get_steps, get_best_record, get_worst_record,
                          compute_delta, is_improving, find_plateau_start,
                          smooth_values, tracker_stats, compare_trackers,
                          merge_trackers, window_stats, top_k_records)
    contour_profile_utils — утилиты профилей контуров и рёбер
                          (ProfileConfig, ProfileMatchResult,
                          sample_profile_along_contour, contour_curvature,
                          smooth_profile, normalize_profile,
                          profile_l2_distance, profile_cosine_similarity,
                          best_cyclic_offset, align_profiles,
                          match_profiles, batch_match_profiles,
                          top_k_profile_matches)
    placement_metrics_utils — утилиты метрик качества размещения
                          (PlacementMetricsConfig, PlacementMetrics,
                          placement_density, bbox_of_contour, bbox_area,
                          bbox_intersection_area, compute_coverage,
                          compute_pairwise_overlap, quality_score,
                          assess_placement, compare_metrics, best_of,
                          normalize_metrics, batch_quality_scores)
    region_score_utils  — утилиты оценки и ранжирования регионов маски
                          (RegionScoreConfig, RegionScore,
                          region_compactness, region_extent, mask_perimeter,
                          score_region, evaluate_region, filter_by_score,
                          rank_regions, top_k_regions, region_score_stats,
                          batch_evaluate_regions,
                          normalize_scores as normalize_region_scores)
    edge_profile_utils  — утилиты профилей краёв фрагментов
                          (EdgeProfileConfig, EdgeProfile,
                          build_edge_profile, profile_l2_distance,
                          profile_cosine_similarity, profile_correlation,
                          resample_profile, flip_profile, mean_profile,
                          batch_build_profiles, pairwise_l2_matrix,
                          best_matching_profile)
    rotation_score_utils — утилиты оценки качества результатов поворота
                          (RotationScoreConfig, RotationScoreEntry,
                          make_entry, filter_by_confidence,
                          filter_by_method, filter_by_angle_range,
                          rank_by_confidence, best_entry, aggregate_angles,
                          rotation_score_stats, angle_agreement,
                          batch_make_entries, top_k_entries,
                          group_by_method)
    overlap_score_utils — утилиты оценки и анализа перекрытий фрагментов
                          (OverlapScoreConfig, OverlapScoreEntry,
                          OverlapSummary, make_overlap_entry,
                          summarise_overlaps, filter_significant_overlaps,
                          filter_by_area, top_k_overlaps, overlap_stats,
                          penalty_score, batch_make_overlap_entries,
                          group_by_fragment)
    placement_score_utils — утилиты оценки размещения фрагментов
                          (PlacementScoreConfig, PlacementScoreEntry,
                          PlacementSummary, make_placement_entry,
                          entries_from_history, summarise_placement,
                          filter_positive_steps, filter_by_min_score,
                          top_k_steps, rank_fragments,
                          placement_score_stats, compare_placements,
                          batch_summarise)
    annealing_score_utils — утилиты оценки качества результатов отжига
                          (AnnealingScoreConfig, AnnealingScoreEntry,
                          AnnealingSummary, make_annealing_entry,
                          entries_from_log, summarise_annealing,
                          filter_accepted, filter_rejected,
                          filter_annealing_by_min_score,
                          filter_by_temperature_range,
                          top_k_annealing_entries, annealing_score_stats,
                          best_annealing_entry, compare_summaries,
                          batch_summarise_annealing)
    consensus_score_utils — утилиты оценки качества консенсуса
                          (ConsensusScoreConfig, ConsensusScoreEntry,
                          ConsensusSummary, make_consensus_entry,
                          entries_from_votes, summarise_consensus,
                          filter_consensus_pairs, filter_non_consensus,
                          filter_by_vote_fraction,
                          top_k_consensus_entries, consensus_score_stats,
                          agreement_score, compare_consensus,
                          batch_summarise_consensus)
    quality_score_utils — утилиты оценки качества фрагментов и изображений
                          (QualityScoreConfig, QualityScoreEntry,
                          QualitySummary, make_quality_entry,
                          entries_from_quality_reports,
                          summarise_quality, filter_quality_acceptable,
                          filter_quality_rejected, filter_by_overall,
                          filter_by_blur, top_k_quality_entries,
                          quality_score_stats, compare_quality,
                          batch_summarise_quality)
    candidate_rank_utils — утилиты ранжирования и фильтрации кандидатных пар
                          (CandidateRankConfig, CandidateRankEntry,
                          CandidateRankSummary, make_candidate_entry,
                          entries_from_candidate_pairs,
                          summarise_rankings, filter_selected_candidates,
                          filter_rejected_candidates,
                          filter_by_score_range, filter_by_rank,
                          top_k_candidate_entries, candidate_rank_stats,
                          compare_rankings, batch_summarise_rankings)
    filter_pipeline_utils — утилиты конвейерной фильтрации кандидатных пар
                          (FilterStepConfig, FilterStepResult,
                          FilterPipelineSummary, make_filter_step,
                          steps_from_log, summarise_pipeline,
                          filter_effective_steps, filter_by_removal_rate,
                          most_aggressive_step, least_aggressive_step,
                          pipeline_stats, compare_pipelines,
                          batch_summarise_pipelines)
    score_norm_utils    — утилиты нормализации и калибровки оценок
                          (ScoreNormConfig, ScoreNormEntry,
                          ScoreNormSummary, make_norm_entry,
                          entries_from_scores, summarise_norm,
                          filter_by_normalized_range, filter_by_original_range,
                          top_k_norm_entries, norm_entry_stats,
                          compare_norm_summaries, batch_summarise_norm)
    shape_match_utils   — утилиты анализа и ранжирования сопоставления форм
                          (ShapeMatchConfig, ShapeMatchEntry,
                          ShapeMatchSummary, make_match_entry,
                          entries_from_results, summarise_matches,
                          filter_good_matches, filter_poor_matches,
                          filter_by_hu_dist, filter_match_by_score_range,
                          top_k_match_entries, match_entry_stats,
                          compare_match_summaries, batch_summarise_matches)
    canvas_build_utils  — утилиты планирования и анализа сборки холста
                          (CanvasBuildConfig, PlacementEntry,
                          CanvasBuildSummary, make_placement_entry,
                          entries_from_placements, summarise_canvas_build,
                          filter_by_area, filter_by_coverage_contribution,
                          top_k_by_coverage, canvas_build_stats,
                          compare_canvas_summaries,
                          batch_summarise_canvas_builds)
    assembly_score_utils — утилиты анализа и ранжирования результатов сборки
                          (AssemblyScoreConfig, AssemblyScoreEntry,
                          AssemblySummary, make_assembly_entry,
                          entries_from_assemblies, summarise_assemblies,
                          filter_good_assemblies, filter_poor_assemblies,
                          filter_by_method, filter_by_score_range,
                          filter_by_min_fragments, top_k_assembly_entries,
                          best_assembly_entry, assembly_score_stats,
                          compare_assembly_summaries,
                          batch_summarise_assemblies)
    patch_score_utils   — утилиты анализа и ранжирования сопоставления патчей
                          (PatchScoreConfig, PatchScoreEntry,
                          PatchScoreSummary, make_patch_entry,
                          entries_from_patch_matches, summarise_patch_scores,
                          filter_good_patch_scores, filter_poor_patch_scores,
                          filter_patch_by_score_range, filter_by_side_pair,
                          filter_by_ncc_range, top_k_patch_entries,
                          best_patch_entry, patch_score_stats,
                          compare_patch_summaries,
                          batch_summarise_patch_scores)
"""
from .logger import (
    get_logger,
    stage,
    ProgressBar,
    PipelineTimer,
    log,
)
from .geometry import (
    rotation_matrix_2d,
    rotate_points,
    polygon_area,
    polygon_centroid,
    bbox_from_points,
    resample_curve,
    align_centroids,
    poly_iou,
    point_in_polygon,
    normalize_contour,
    smooth_contour,
    curvature,
)
from .cache import (
    DescriptorCache,
    DiskCache,
    descriptor_key,
    cached,
    get_default_cache,
    clear_default_cache,
)
from .io import (
    load_image_dir,
    fragments_from_images,
    save_assembly_json,
    load_assembly_json,
    save_fragments_npz,
    load_fragments_npz,
    FragmentSetInfo,
)
from .profiler import (
    StepProfile,
    PipelineProfiler,
    profile_function,
    timed,
    format_duration,
    compare_profilers,
)
from .visualizer import (
    VisConfig,
    draw_word_boxes,
    draw_fragment_boxes,
    draw_edge_matches,
    draw_contour,
    draw_assembly_layout,
    draw_skew_angle,
    draw_confidence_bar,
    tile_images,
)
from .metrics import (
    ReconstructionMetrics as AssemblyReconstructionMetrics,
    placement_iou,
    order_kendall_tau,
    permutation_distance,
    assembly_precision_recall,
    fragment_placement_accuracy,
    compute_reconstruction_metrics,
)
from .image_stats import (
    ImageStats,
    compute_entropy,
    compute_sharpness,
    compute_histogram_stats,
    compute_gradient_stats,
    compute_image_stats,
    compare_images,
    batch_stats,
)
from .patch_extractor import (
    Patch,
    PatchSet,
    extract_grid_patches,
    extract_sliding_patches,
    extract_random_patches,
    extract_border_patches,
    filter_patches,
    batch_extract_patches,
)
from .image_io import (
    ImageRecord,
    load_image,
    save_image,
    load_directory,
    filter_by_extension,
    parse_fragment_id,
    resize_to_max,
    batch_resize,
)
from .transform_utils import (
    rotate_image,
    flip_image,
    scale_image,
    crop_region,
    affine_from_params,
    compose_affines,
    apply_affine,
    apply_homography,
    batch_rotate,
)
from .color_utils import (
    to_gray,
    to_lab,
    to_hsv,
    from_lab,
    compute_histogram,
    compare_histograms,
    dominant_colors,
    color_distance,
    strip_histogram,
)
from .mask_utils import (
    create_alpha_mask,
    apply_mask,
    erode_mask,
    dilate_mask,
    mask_from_contour,
    combine_masks,
    crop_to_mask,
    invert_mask,
)
from .array_utils import (
    normalize_array,
    pad_to_shape,
    crop_center,
    stack_arrays,
    chunk_array,
    sliding_window,
    flatten_images,
    unflatten_images,
    compute_pairwise_norms,
)
from .contour_utils import (
    simplify_contour,
    interpolate_contour,
    contour_area,
    contour_perimeter,
    contour_bbox,
    contour_centroid,
    contour_iou,
    align_contour_orientation,
    contours_to_mask,
    mask_to_contour,
)
from .histogram_utils import (
    compute_1d_histogram,
    compute_2d_histogram,
    histogram_equalization,
    histogram_specification,
    earth_mover_distance,
    chi_squared_distance,
    histogram_intersection,
    backproject,
    joint_histogram,
)
from .keypoint_utils import (
    KeypointSet,
    detect_keypoints,
    filter_by_response,
    filter_by_region,
    describe_keypoints,
    match_descriptors,
    filter_matches_ransac,
    keypoints_to_array,
    array_to_keypoints,
    compute_match_score,
)
from .signal_utils import (
    smooth_signal,
    normalize_signal,
    find_peaks,
    find_valleys,
    compute_autocorrelation,
    compute_cross_correlation,
    signal_energy,
    segment_signal,
    resample_signal,
    phase_shift,
)
from .bbox_utils import (
    BBox,
    bbox_iou,
    bbox_intersection,
    bbox_union,
    expand_bbox,
    crop_image,
    bboxes_from_mask,
    merge_overlapping_bboxes,
    bbox_center,
    bbox_aspect_ratio,
)
from .sparse_utils import (
    SparseEntry,
    to_sparse_entries,
    from_sparse_entries,
    sparse_top_k,
    threshold_matrix,
    symmetrize_matrix,
    normalize_matrix,
    diagonal_zeros,
    matrix_sparsity,
    top_k_per_row,
)
from .clustering_utils import (
    ClusterResult,
    kmeans_cluster,
    assign_to_clusters,
    compute_inertia,
    silhouette_score_approx,
    hierarchical_cluster,
    find_optimal_k,
    cluster_indices,
    merge_clusters,
)
from .distance_utils import (
    euclidean_distance,
    cosine_distance,
    cosine_similarity,
    manhattan_distance,
    chebyshev_distance,
    hausdorff_distance,
    chamfer_distance,
    normalized_distance,
    pairwise_distances,
    nearest_neighbor_dist,
)
from .smoothing_utils import (
    SmoothingParams,
    moving_average,
    gaussian_smooth,
    median_smooth,
    exponential_smooth,
    savgol_smooth,
    smooth_contour as smooth_contour_signal,
    apply_smoothing,
    batch_smooth,
)
from .feature_selector import (
    FeatureSet,
    SelectionResult,
    variance_selection,
    correlation_selection,
    rank_features,
    pca_reduce,
    normalize_features,
    select_top_k,
    apply_selection,
    batch_select,
)
from .graph_utils import (
    GraphEdge,
    FragmentGraph,
    build_graph,
    dijkstra,
    shortest_path,
    minimum_spanning_tree,
    connected_components,
    node_degrees,
    subgraph,
    batch_build_graphs,
)
from .cache_manager import (
    CacheEntry,
    CacheStats,
    LRUCache,
    make_cache,
    cached_call,
    merge_caches,
)
from .progress_tracker import (
    StepRecord,
    PipelineReport,
    ProgressTracker,
    make_tracker,
    run_step,
    summarize_tracker,
)
from .config_manager import (
    ConfigField,
    ConfigSpec,
    ConfigSnapshot,
    validate_field_type,
    validate_config,
    load_config,
    merge_configs,
    diff_configs,
    make_config_snapshot,
    batch_validate as batch_validate_configs,
)
from .result_cache import (
    CachePolicy,
    CacheRecord,
    CacheSummary,
    ResultCache,
    make_cache as make_result_cache,
    cached_result,
    merge_caches as merge_result_caches,
    evict_expired,
)
from .metric_tracker import (
    MetricRecord,
    MetricStats,
    TrackerConfig,
    MetricTracker,
    make_tracker as make_metric_tracker,
    merge_trackers,
    compute_moving_average,
    export_metrics,
)
from .event_log import (
    EventLogConfig,
    EventRecord,
    EventSummary,
    EventLog,
    make_event_log,
    log_event,
    filter_events,
    summarize_events,
    merge_event_logs,
    export_event_log,
)
from .batch_processor import (
    ProcessConfig,
    ProcessItem,
    BatchSummary,
    make_processor,
    process_items,
    filter_successful,
    retry_failed_items,
    split_batch,
    merge_batch_results,
)
from .event_bus import (
    BusConfig,
    EventRecord,
    BusSummary,
    EventBus,
    make_event_bus,
    collect_events,
    drain_bus,
)
from .pipeline_runner import (
    RunnerConfig,
    StepResult,
    PipelineResult,
    PipelineStep,
    make_step,
    run_pipeline,
    get_step_output,
    filter_step_results,
    retry_failed_steps,
)
from .polygon_utils import (
    polygon_area as poly_area,
    polygon_perimeter,
    polygon_centroid as poly_centroid,
    point_in_polygon as poly_point_in,
    convex_hull,
    polygon_bounding_box,
    polygon_aspect_ratio,
    translate_polygon,
    scale_polygon,
    rotate_polygon,
    polygon_similarity,
)
from .score_aggregator import (
    AggregationMethod,
    ScoreVector,
    AggregationResult,
    weighted_sum,
    harmonic_mean,
    geometric_mean,
    aggregate_pair,
    aggregate_matrix,
    top_k_pairs,
    batch_aggregate,
)
from .normalization_utils import (
    l1_normalize,
    l2_normalize,
    minmax_normalize,
    zscore_normalize,
    softmax,
    clamp,
    symmetrize_matrix,
    zero_diagonal,
    normalize_rows,
    batch_l2_normalize,
)
from .tile_utils import (
    TileConfig,
    Tile,
    tile_image,
    reassemble_tiles,
    tile_overlap_ratio,
    filter_tiles_by_content,
    compute_tile_grid,
    batch_tile_images,
)
from .distance_matrix import (
    DistanceConfig,
    euclidean_distance_matrix,
    cosine_distance_matrix,
    manhattan_distance_matrix,
    build_distance_matrix,
    normalize_distance_matrix,
    to_similarity_matrix,
    threshold_distance_matrix,
    top_k_distance_pairs,
)
from .edge_profiler import (
    ProfileConfig,
    EdgeProfile,
    compute_brightness_profile,
    compute_gradient_profile,
    compute_diff_profile,
    normalize_profile,
    aggregate_profiles,
    compare_profiles,
    batch_profile_edges,
)
from .contour_sampler import (
    SamplerConfig,
    SampledContour,
    sample_uniform,
    sample_curvature,
    sample_random,
    sample_corners,
    sample_contour,
    normalize_contour as normalize_sampled_contour,
    batch_sample as batch_sample_contours,
)
from .frequency_utils import (
    FrequencyConfig,
    compute_fft_magnitude,
    radial_power_spectrum,
    frequency_band_energy,
    high_frequency_ratio,
    low_pass_filter,
    high_pass_filter,
    compare_frequency_spectra,
)
from .morph_utils import (
    MorphConfig,
    apply_erosion,
    apply_dilation,
    apply_opening,
    apply_closing,
    get_skeleton,
    label_regions,
    filter_regions_by_size,
    compute_region_stats,
    batch_morphology,
)
from .voting_utils import (
    VoteConfig,
    cast_pair_votes,
    aggregate_pair_votes,
    cast_position_votes,
    majority_vote,
    weighted_vote,
    rank_fusion,
    batch_vote,
)
from .patch_utils import (
    PatchConfig,
    extract_patch,
    extract_patches,
    normalize_patch,
    compare_patches,
    patch_ssd,
    patch_ncc,
    patch_mse,
    batch_compare,
)
from .blend_utils import (
    BlendConfig,
    alpha_blend,
    weighted_blend,
    feather_mask,
    paste_with_mask,
    horizontal_blend,
    vertical_blend,
    batch_blend,
)
from .gradient_utils import (
    GradientConfig,
    compute_gradient_magnitude,
    compute_gradient_direction,
    compute_sobel,
    compute_laplacian,
    threshold_gradient,
    suppress_non_maximum,
    compute_edge_density,
    batch_compute_gradients,
)
from .text_utils import (
    TextConfig,
    TextBlock,
    clean_ocr_text,
    estimate_text_density,
    find_text_lines,
    segment_words,
    compute_text_score,
    compare_text_blocks,
    align_text_blocks,
    batch_clean_text,
)
from .sequence_utils import (
    SequenceConfig,
    rank_sequence,
    normalize_sequence,
    invert_sequence,
    sliding_scores,
    align_sequences,
    kendall_tau_distance,
    longest_increasing,
    segment_by_threshold,
    batch_rank,
)
from .topology_utils import (
    TopologyConfig,
    compute_euler_number,
    count_holes,
    compute_solidity,
    compute_extent,
    compute_convexity,
    compute_compactness,
    is_simply_connected,
    shape_complexity,
    batch_topology,
)
from .curvature_utils import (
    CurvatureConfig,
    compute_curvature,
    compute_total_curvature,
    find_inflection_points,
    compute_turning_angle,
    smooth_curvature,
    corner_score,
    find_corners,
    batch_curvature,
)
from .window_utils import (
    WindowConfig,
    apply_window_function,
    rolling_mean,
    rolling_std,
    rolling_max,
    rolling_min,
    compute_overlap,
    split_into_windows,
    merge_windows,
    batch_rolling,
)
from .stats_utils import (
    StatsConfig,
    describe,
    zscore_array,
    iqr,
    winsorize,
    percentile_rank,
    outlier_mask,
    running_stats,
    weighted_mean,
    weighted_std,
    batch_describe,
)
from .threshold_utils import (
    ThresholdConfig,
    apply_threshold,
    binarize,
    adaptive_threshold,
    soft_threshold,
    threshold_matrix as threshold_score_matrix,
    hysteresis_threshold,
    otsu_threshold,
    count_above,
    fraction_above,
    batch_threshold,
)
from .interpolation_utils import (
    InterpolationConfig,
    lerp,
    lerp_array,
    bilinear_interpolate,
    resample_1d,
    fill_missing,
    interpolate_scores,
    smooth_interpolate,
    batch_resample,
)
from .sampling_utils import (
    SamplingConfig,
    uniform_sample,
    sample_angle,
    sample_position,
    sample_positions_grid,
    sample_permutation,
    weighted_sample,
    acceptance_probability,
    sample_swap_pair,
    batch_uniform_sample,
)
from .edge_scorer import (
    EdgeScoreConfig,
    EdgeScoreResult,
    score_edge_overlap,
    score_edge_curvature,
    score_edge_length,
    score_edge_endpoints,
    aggregate_edge_scores,
    rank_edge_pairs,
    batch_score_edges,
)
from .annealing_schedule import (
    ScheduleConfig,
    TemperatureRecord,
    linear_schedule,
    geometric_schedule,
    exponential_schedule,
    cosine_schedule,
    stepped_schedule,
    get_temperature,
    estimate_steps,
    batch_temperatures,
)
from .rotation_utils import (
    RotationConfig,
    rotate_image_angle,
    rotate_points_angle,
    normalize_angle,
    angle_difference,
    nearest_discrete,
    angles_to_matrix,
    batch_rotate_images,
    estimate_rotation,
)
from .fragment_stats import (
    FragmentMetrics,
    CollectionStats,
    compute_fragment_metrics,
    compute_collection_stats,
    area_histogram,
    compare_collections,
    outlier_indices,
)
from .spatial_index import (
    SpatialConfig,
    SpatialEntry,
    SpatialIndex,
    build_spatial_index,
    query_radius,
    query_knn,
    pairwise_distances,
    cluster_by_distance,
)
from .alignment_utils import (
    AlignmentConfig,
    AlignmentResult,
    normalize_for_alignment,
    find_best_rotation,
    find_best_translation,
    compute_alignment_error,
    align_curves_procrustes,
    align_curves_icp,
    alignment_score,
    batch_align_curves,
)
from .curve_metrics import (
    CurveMetricConfig,
    CurveComparisonResult,
    curve_l2,
    curve_l2_mirror,
    hausdorff_distance,
    frechet_distance_approx,
    curve_length,
    length_ratio,
    compare_curves,
    batch_compare_curves,
)
from .segment_utils import (
    SegmentConfig,
    RegionInfo,
    label_mask,
    region_info,
    all_regions,
    filter_regions,
    largest_region,
    mask_from_labels,
    mask_statistics,
    mask_bounding_box,
    extract_boundary,
)
from .polygon_ops_utils import (
    PolygonOpsConfig,
    PolygonOverlapResult,
    PolygonStats,
    signed_area,
    polygon_area as poly_ops_area,
    polygon_perimeter as poly_ops_perimeter,
    polygon_centroid as poly_ops_centroid,
    polygon_bounding_box as poly_ops_bbox,
    polygon_stats,
    point_in_polygon as poly_ops_point_in,
    polygon_overlap,
    remove_collinear,
    ensure_ccw,
    ensure_cw,
    polygon_similarity as poly_ops_similarity,
    batch_polygon_stats,
    batch_polygon_overlap,
)
from .score_matrix_utils import (
    ScoreMatrixConfig,
    MatrixStats,
    RankEntry,
    zero_diagonal,
    symmetrize,
    threshold_matrix as threshold_score_mat,
    normalize_rows as normalize_score_rows,
    top_k_indices,
    matrix_stats,
    top_k_per_row as score_top_k_per_row,
    filter_by_threshold,
    intra_fragment_mask,
    apply_intra_fragment_mask,
    batch_matrix_stats,
)
from .image_transform_utils import (
    ImageTransformConfig,
    TransformResult,
    rotate_image as img_rotate,
    flip_horizontal,
    flip_vertical,
    pad_image,
    crop_image as crop_img,
    resize_image,
    resize_to_max_side,
    apply_affine as apply_affine_transform,
    rotation_matrix_2x3,
    batch_rotate as batch_rotate_images_v2,
    batch_pad,
    batch_resize_to_max,
)
from .fragment_filter_utils import (
    FragmentFilterConfig,
    FragmentQuality,
    compute_fragment_area,
    compute_aspect_ratio,
    compute_fill_ratio,
    evaluate_fragment,
    deduplicate_fragments,
    filter_fragments,
    sort_by_area,
    top_k_fragments,
    fragment_quality_summary,
)
from .config_utils import (
    validate_section,
    validate_range,
    merge_dicts,
    flatten_dict,
    unflatten_dict,
    overrides_from_env,
    ConfigProfile,
    PROFILES,
    apply_profile,
    list_profiles,
    load_json_config,
    save_json_config,
    diff_configs,
)
from .icp_utils import (
    ICPConfig,
    centroid,
    center_points,
    scale_points,
    resample_uniform,
    nearest_neighbours,
    filter_correspondences,
    svd_rotation,
    svd_translation,
    compute_rmse,
    rmse_after_transform,
    has_converged,
    compose_transforms,
    invert_transform,
    PairAlignResult,
    batch_nearest_neighbours,
    transform_points,
    align_to_first,
)
from .descriptor_utils import (
    DescriptorConfig,
    l2_normalize as desc_l2_normalize,
    l1_normalize as desc_l1_normalize,
    batch_l2_normalize as desc_batch_l2_normalize,
    l2_distance,
    cosine_distance,
    chi2_distance,
    l1_distance,
    descriptor_distance as desc_distance,
    pairwise_l2,
    pairwise_cosine,
    DescriptorMatch,
    nn_match,
    ratio_test,
    mean_pool,
    max_pool,
    vlad_encode,
    batch_nn_match,
    top_k_matches,
    filter_matches_by_distance as filter_desc_matches,
)
from .render_utils import (
    CanvasConfig,
    MosaicConfig,
    rotation_matrix_2d as render_rotation_matrix_2d,
    bounding_box_of_rotated,
    compute_canvas_size,
    make_blank_canvas,
    resize_keep_aspect,
    pad_to_square,
    make_thumbnail,
    paste_with_mask as render_paste_with_mask,
    compute_grid_layout,
    make_mosaic,
    save_image as render_save_image,
    horizontal_concat,
)
from .tracker_utils import (
    TrackerConfig,
    StepRecord,
    IterTracker,
    create_iter_tracker,
    record_step,
    get_values,
    get_steps,
    get_best_record,
    get_worst_record,
    compute_delta,
    is_improving,
    find_plateau_start,
    smooth_values,
    tracker_stats,
    compare_trackers,
    merge_trackers,
    window_stats,
    top_k_records,
)
from .contour_profile_utils import (
    ProfileConfig,
    ProfileMatchResult,
    sample_profile_along_contour,
    contour_curvature,
    smooth_profile,
    normalize_profile as normalize_profile_values,
    profile_l2_distance,
    profile_cosine_similarity,
    best_cyclic_offset,
    align_profiles,
    match_profiles,
    batch_match_profiles,
    top_k_profile_matches,
)
from .placement_metrics_utils import (
    PlacementMetricsConfig,
    PlacementMetrics,
    placement_density,
    bbox_of_contour,
    bbox_area,
    bbox_intersection_area,
    compute_coverage,
    compute_pairwise_overlap,
    quality_score as placement_quality_score,
    assess_placement,
    compare_metrics as compare_placement_metrics,
    best_of as best_placement_of,
    normalize_metrics as normalize_placement_metrics,
    batch_quality_scores as batch_placement_quality_scores,
)
from .region_score_utils import (
    RegionScoreConfig,
    RegionScore,
    region_compactness,
    region_extent,
    mask_perimeter,
    score_region,
    evaluate_region,
    filter_by_score as filter_regions_by_score,
    rank_regions,
    top_k_regions,
    region_score_stats,
    batch_evaluate_regions,
    normalize_scores as normalize_region_scores,
)
from .edge_profile_utils import (
    EdgeProfileConfig,
    EdgeProfile,
    build_edge_profile,
    profile_l2_distance,
    profile_cosine_similarity,
    profile_correlation,
    resample_profile,
    flip_profile,
    mean_profile,
    batch_build_profiles,
    pairwise_l2_matrix,
    best_matching_profile,
)
from .rotation_score_utils import (
    RotationScoreConfig,
    RotationScoreEntry,
    make_entry as make_rotation_entry,
    filter_by_confidence as filter_rotations_by_confidence,
    filter_by_method as filter_rotations_by_method,
    filter_by_angle_range,
    rank_by_confidence as rank_rotations_by_confidence,
    best_entry as best_rotation_entry,
    aggregate_angles,
    rotation_score_stats,
    angle_agreement,
    batch_make_entries as batch_make_rotation_entries,
    top_k_entries as top_k_rotation_entries,
    group_by_method as group_rotations_by_method,
)
from .overlap_score_utils import (
    OverlapScoreConfig,
    OverlapScoreEntry,
    OverlapSummary,
    make_overlap_entry,
    summarise_overlaps,
    filter_significant_overlaps,
    filter_by_area as filter_overlaps_by_area,
    top_k_overlaps,
    overlap_stats,
    penalty_score,
    batch_make_overlap_entries,
    group_by_fragment,
)
from .placement_score_utils import (
    PlacementScoreConfig,
    PlacementScoreEntry,
    PlacementSummary,
    make_placement_entry,
    entries_from_history,
    summarise_placement,
    filter_positive_steps,
    filter_by_min_score as filter_placements_by_min_score,
    top_k_steps,
    rank_fragments,
    placement_score_stats,
    compare_placements,
    batch_summarise as batch_summarise_placements,
)
from .annealing_score_utils import (
    AnnealingScoreConfig,
    AnnealingScoreEntry,
    AnnealingSummary,
    make_annealing_entry,
    entries_from_log,
    summarise_annealing,
    filter_accepted,
    filter_rejected,
    filter_by_min_score as filter_annealing_by_min_score,
    filter_by_temperature_range,
    top_k_entries as top_k_annealing_entries,
    annealing_score_stats,
    best_entry as best_annealing_entry,
    compare_summaries,
    batch_summarise as batch_summarise_annealing,
)
from .consensus_score_utils import (
    ConsensusScoreConfig,
    ConsensusScoreEntry,
    ConsensusSummary,
    make_consensus_entry,
    entries_from_votes,
    summarise_consensus,
    filter_consensus_pairs,
    filter_non_consensus,
    filter_by_vote_fraction,
    top_k_consensus_entries,
    consensus_score_stats,
    agreement_score,
    compare_consensus,
    batch_summarise_consensus,
)
from .quality_score_utils import (
    QualityScoreConfig,
    QualityScoreEntry,
    QualitySummary,
    make_quality_entry,
    entries_from_reports as entries_from_quality_reports,
    summarise_quality,
    filter_acceptable as filter_quality_acceptable,
    filter_rejected as filter_quality_rejected,
    filter_by_overall,
    filter_by_blur,
    top_k_quality_entries,
    quality_score_stats,
    compare_quality,
    batch_summarise_quality,
)
from .candidate_rank_utils import (
    CandidateRankConfig,
    CandidateRankEntry,
    CandidateRankSummary,
    make_candidate_entry,
    entries_from_pairs as entries_from_candidate_pairs,
    summarise_rankings,
    filter_selected as filter_selected_candidates,
    filter_rejected_candidates,
    filter_by_score_range,
    filter_by_rank,
    top_k_candidate_entries,
    candidate_rank_stats,
    compare_rankings,
    batch_summarise_rankings,
)
from .filter_pipeline_utils import (
    FilterStepConfig,
    FilterStepResult,
    FilterPipelineSummary,
    make_filter_step,
    steps_from_log,
    summarise_pipeline,
    filter_effective_steps,
    filter_by_removal_rate,
    most_aggressive_step,
    least_aggressive_step,
    pipeline_stats,
    compare_pipelines,
    batch_summarise_pipelines,
)
from .score_norm_utils import (
    ScoreNormConfig,
    ScoreNormEntry,
    ScoreNormSummary,
    make_norm_entry,
    entries_from_scores,
    summarise_norm,
    filter_by_normalized_range,
    filter_by_original_range,
    top_k_norm_entries,
    norm_entry_stats,
    compare_norm_summaries,
    batch_summarise_norm,
)
from .shape_match_utils import (
    ShapeMatchConfig,
    ShapeMatchEntry,
    ShapeMatchSummary,
    make_match_entry,
    entries_from_results as entries_from_match_results,
    summarise_matches,
    filter_good_matches,
    filter_poor_matches,
    filter_by_hu_dist,
    filter_match_by_score_range,
    top_k_match_entries,
    match_entry_stats,
    compare_match_summaries,
    batch_summarise_matches,
)
from .canvas_build_utils import (
    CanvasBuildConfig,
    PlacementEntry,
    CanvasBuildSummary,
    make_placement_entry,
    entries_from_placements,
    summarise_canvas_build,
    filter_by_area,
    filter_by_coverage_contribution,
    top_k_by_coverage,
    canvas_build_stats,
    compare_canvas_summaries,
    batch_summarise_canvas_builds,
)
from .assembly_score_utils import (
    AssemblyScoreConfig,
    AssemblyScoreEntry,
    AssemblySummary,
    make_assembly_entry,
    entries_from_assemblies,
    summarise_assemblies,
    filter_good_assemblies,
    filter_poor_assemblies,
    filter_by_method as filter_assemblies_by_method,
    filter_by_score_range as filter_assemblies_by_score_range,
    filter_by_min_fragments,
    top_k_assembly_entries,
    best_assembly_entry,
    assembly_score_stats,
    compare_assembly_summaries,
    batch_summarise_assemblies,
)
from .patch_score_utils import (
    PatchScoreConfig,
    PatchScoreEntry,
    PatchScoreSummary,
    make_patch_entry,
    entries_from_patch_matches,
    summarise_patch_scores,
    filter_good_patch_scores,
    filter_poor_patch_scores,
    filter_patch_by_score_range,
    filter_by_side_pair,
    filter_by_ncc_range,
    top_k_patch_entries,
    best_patch_entry,
    patch_score_stats,
    compare_patch_summaries,
    batch_summarise_patch_scores,
)

__all__ = [
    # Логирование
    "get_logger",
    "stage",
    "ProgressBar",
    "PipelineTimer",
    "log",
    # Геометрия
    "rotation_matrix_2d",
    "rotate_points",
    "polygon_area",
    "polygon_centroid",
    "bbox_from_points",
    "resample_curve",
    "align_centroids",
    "poly_iou",
    "point_in_polygon",
    "normalize_contour",
    "smooth_contour",
    "curvature",
    # Кэш
    "DescriptorCache",
    "DiskCache",
    "descriptor_key",
    "cached",
    "get_default_cache",
    "clear_default_cache",
    # Ввод-вывод
    "load_image_dir",
    "fragments_from_images",
    "save_assembly_json",
    "load_assembly_json",
    "save_fragments_npz",
    "load_fragments_npz",
    "FragmentSetInfo",
    # Профилировщик
    "StepProfile",
    "PipelineProfiler",
    "profile_function",
    "timed",
    "format_duration",
    "compare_profilers",
    # Визуализация
    "VisConfig",
    "draw_word_boxes",
    "draw_fragment_boxes",
    "draw_edge_matches",
    "draw_contour",
    "draw_assembly_layout",
    "draw_skew_angle",
    "draw_confidence_bar",
    "tile_images",
    # Метрики качества
    "AssemblyReconstructionMetrics",
    "placement_iou",
    "order_kendall_tau",
    "permutation_distance",
    "assembly_precision_recall",
    "fragment_placement_accuracy",
    "compute_reconstruction_metrics",
    # Статистический анализ изображений
    "ImageStats",
    "compute_entropy",
    "compute_sharpness",
    "compute_histogram_stats",
    "compute_gradient_stats",
    "compute_image_stats",
    "compare_images",
    "batch_stats",
    # Извлечение патчей
    "Patch",
    "PatchSet",
    "extract_grid_patches",
    "extract_sliding_patches",
    "extract_random_patches",
    "extract_border_patches",
    "filter_patches",
    "batch_extract_patches",
    # Ввод-вывод изображений
    "ImageRecord",
    "load_image",
    "save_image",
    "load_directory",
    "filter_by_extension",
    "parse_fragment_id",
    "resize_to_max",
    "batch_resize",
    # Геометрические преобразования
    "rotate_image",
    "flip_image",
    "scale_image",
    "crop_region",
    "affine_from_params",
    "compose_affines",
    "apply_affine",
    "apply_homography",
    "batch_rotate",
    # Цветовые утилиты
    "to_gray",
    "to_lab",
    "to_hsv",
    "from_lab",
    "compute_histogram",
    "compare_histograms",
    "dominant_colors",
    "color_distance",
    "strip_histogram",
    # Утилиты масок
    "create_alpha_mask",
    "apply_mask",
    "erode_mask",
    "dilate_mask",
    "mask_from_contour",
    "combine_masks",
    "crop_to_mask",
    "invert_mask",
    # Утилиты numpy-массивов
    "normalize_array",
    "pad_to_shape",
    "crop_center",
    "stack_arrays",
    "chunk_array",
    "sliding_window",
    "flatten_images",
    "unflatten_images",
    "compute_pairwise_norms",
    # Утилиты контуров
    "simplify_contour",
    "interpolate_contour",
    "contour_area",
    "contour_perimeter",
    "contour_bbox",
    "contour_centroid",
    "contour_iou",
    "align_contour_orientation",
    "contours_to_mask",
    "mask_to_contour",
    # Утилиты гистограмм
    "compute_1d_histogram",
    "compute_2d_histogram",
    "histogram_equalization",
    "histogram_specification",
    "earth_mover_distance",
    "chi_squared_distance",
    "histogram_intersection",
    "backproject",
    "joint_histogram",
    # Утилиты ключевых точек
    "KeypointSet",
    "detect_keypoints",
    "filter_by_response",
    "filter_by_region",
    "describe_keypoints",
    "match_descriptors",
    "filter_matches_ransac",
    "keypoints_to_array",
    "array_to_keypoints",
    "compute_match_score",
    # 1D обработка сигналов
    "smooth_signal",
    "normalize_signal",
    "find_peaks",
    "find_valleys",
    "compute_autocorrelation",
    "compute_cross_correlation",
    "signal_energy",
    "segment_signal",
    "resample_signal",
    "phase_shift",
    # Утилиты ограничивающих прямоугольников
    "BBox",
    "bbox_iou",
    "bbox_intersection",
    "bbox_union",
    "expand_bbox",
    "crop_image",
    "bboxes_from_mask",
    "merge_overlapping_bboxes",
    "bbox_center",
    "bbox_aspect_ratio",
    # Утилиты разреженных матриц оценок
    "SparseEntry",
    "to_sparse_entries",
    "from_sparse_entries",
    "sparse_top_k",
    "threshold_matrix",
    "symmetrize_matrix",
    "normalize_matrix",
    "diagonal_zeros",
    "matrix_sparsity",
    "top_k_per_row",
    # Кластеризация фрагментов
    "ClusterResult",
    "kmeans_cluster",
    "assign_to_clusters",
    "compute_inertia",
    "silhouette_score_approx",
    "hierarchical_cluster",
    "find_optimal_k",
    "cluster_indices",
    "merge_clusters",
    # Метрики расстояния и сходства
    "euclidean_distance",
    "cosine_distance",
    "cosine_similarity",
    "manhattan_distance",
    "chebyshev_distance",
    "hausdorff_distance",
    "chamfer_distance",
    "normalized_distance",
    "pairwise_distances",
    "nearest_neighbor_dist",
    # Сглаживание сигналов и контуров
    "SmoothingParams",
    "moving_average",
    "gaussian_smooth",
    "median_smooth",
    "exponential_smooth",
    "savgol_smooth",
    "smooth_contour_signal",
    "apply_smoothing",
    "batch_smooth",
    # Выбор признаков
    "FeatureSet",
    "SelectionResult",
    "variance_selection",
    "correlation_selection",
    "rank_features",
    "pca_reduce",
    "normalize_features",
    "select_top_k",
    "apply_selection",
    "batch_select",
    # Граф совместимости фрагментов
    "GraphEdge",
    "FragmentGraph",
    "build_graph",
    "dijkstra",
    "shortest_path",
    "minimum_spanning_tree",
    "connected_components",
    "node_degrees",
    "subgraph",
    "batch_build_graphs",
    # LRU-кэш
    "CacheEntry",
    "CacheStats",
    "LRUCache",
    "make_cache",
    "cached_call",
    "merge_caches",
    # Трекер прогресса пайплайна
    "StepRecord",
    "PipelineReport",
    "ProgressTracker",
    "make_tracker",
    "run_step",
    "summarize_tracker",
    # Управление конфигурацией
    "ConfigField",
    "ConfigSpec",
    "ConfigSnapshot",
    "validate_field_type",
    "validate_config",
    "load_config",
    "merge_configs",
    "diff_configs",
    "make_config_snapshot",
    "batch_validate_configs",
    # Кэш промежуточных результатов
    "CachePolicy",
    "CacheRecord",
    "CacheSummary",
    "ResultCache",
    "make_result_cache",
    "cached_result",
    "merge_result_caches",
    "evict_expired",
    # Отслеживание метрик
    "MetricRecord",
    "MetricStats",
    "TrackerConfig",
    "MetricTracker",
    "make_metric_tracker",
    "merge_trackers",
    "compute_moving_average",
    "export_metrics",
    # Журнал событий пайплайна
    "EventLogConfig",
    "EventRecord",
    "EventSummary",
    "EventLog",
    "make_event_log",
    "log_event",
    "filter_events",
    "summarize_events",
    "merge_event_logs",
    "export_event_log",
    # Пакетная обработка элементов
    "ProcessConfig",
    "ProcessItem",
    "BatchSummary",
    "make_processor",
    "process_items",
    "filter_successful",
    "retry_failed_items",
    "split_batch",
    "merge_batch_results",
    # Шина событий pub/sub
    "BusConfig",
    "EventRecord",
    "BusSummary",
    "EventBus",
    "make_event_bus",
    "collect_events",
    "drain_bus",
    # Запуск многоэтапного пайплайна
    "RunnerConfig",
    "StepResult",
    "PipelineResult",
    "PipelineStep",
    "make_step",
    "run_pipeline",
    "get_step_output",
    "filter_step_results",
    "retry_failed_steps",
    # Геометрия полигонов
    "poly_area",
    "polygon_perimeter",
    "poly_centroid",
    "poly_point_in",
    "convex_hull",
    "polygon_bounding_box",
    "polygon_aspect_ratio",
    "translate_polygon",
    "scale_polygon",
    "rotate_polygon",
    "polygon_similarity",
    # Агрегация оценок совместимости
    "AggregationMethod",
    "ScoreVector",
    "AggregationResult",
    "weighted_sum",
    "harmonic_mean",
    "geometric_mean",
    "aggregate_pair",
    "aggregate_matrix",
    "top_k_pairs",
    "batch_aggregate",
    # Нормализация дескрипторов и векторов оценок
    "l1_normalize",
    "l2_normalize",
    "minmax_normalize",
    "zscore_normalize",
    "softmax",
    "clamp",
    "symmetrize_matrix",
    "zero_diagonal",
    "normalize_rows",
    "batch_l2_normalize",
    # Разбивка изображений на тайлы
    "TileConfig",
    "Tile",
    "tile_image",
    "reassemble_tiles",
    "tile_overlap_ratio",
    "filter_tiles_by_content",
    "compute_tile_grid",
    "batch_tile_images",
    # Дискретизация контуров
    "SamplerConfig",
    "SampledContour",
    "sample_uniform",
    "sample_curvature",
    "sample_random",
    "sample_corners",
    "sample_contour",
    "normalize_sampled_contour",
    "batch_sample_contours",
    # Частотный анализ
    "FrequencyConfig",
    "compute_fft_magnitude",
    "radial_power_spectrum",
    "frequency_band_energy",
    "high_frequency_ratio",
    "low_pass_filter",
    "high_pass_filter",
    "compare_frequency_spectra",
    # Морфологическая обработка
    "MorphConfig",
    "apply_erosion",
    "apply_dilation",
    "apply_opening",
    "apply_closing",
    "get_skeleton",
    "label_regions",
    "filter_regions_by_size",
    "compute_region_stats",
    "batch_morphology",
    # Голосование и консенсус
    "VoteConfig",
    "cast_pair_votes",
    "aggregate_pair_votes",
    "cast_position_votes",
    "majority_vote",
    "weighted_vote",
    "rank_fusion",
    "batch_vote",
    # Патчи
    "PatchConfig",
    "extract_patch",
    "extract_patches",
    "normalize_patch",
    "compare_patches",
    "patch_ssd",
    "patch_ncc",
    "patch_mse",
    "batch_compare",
    # Утилиты анализа текста
    "TextConfig",
    "TextBlock",
    "clean_ocr_text",
    "estimate_text_density",
    "find_text_lines",
    "segment_words",
    "compute_text_score",
    "compare_text_blocks",
    "align_text_blocks",
    "batch_clean_text",
    # Смешивание и наложение изображений
    "BlendConfig",
    "alpha_blend",
    "weighted_blend",
    "feather_mask",
    "paste_with_mask",
    "horizontal_blend",
    "vertical_blend",
    "batch_blend",
    # Градиентный анализ изображений
    "GradientConfig",
    "compute_gradient_magnitude",
    "compute_gradient_direction",
    "compute_sobel",
    "compute_laplacian",
    "threshold_gradient",
    "suppress_non_maximum",
    "compute_edge_density",
    "batch_compute_gradients",
    # Операции над последовательностями
    "SequenceConfig",
    "rank_sequence",
    "normalize_sequence",
    "invert_sequence",
    "sliding_scores",
    "align_sequences",
    "kendall_tau_distance",
    "longest_increasing",
    "segment_by_threshold",
    "batch_rank",
    # Топологические утилиты
    "TopologyConfig",
    "compute_euler_number",
    "count_holes",
    "compute_solidity",
    "compute_extent",
    "compute_convexity",
    "compute_compactness",
    "is_simply_connected",
    "shape_complexity",
    "batch_topology",
    # Утилиты кривизны контуров
    "CurvatureConfig",
    "compute_curvature",
    "compute_total_curvature",
    "find_inflection_points",
    "compute_turning_angle",
    "smooth_curvature",
    "corner_score",
    "find_corners",
    "batch_curvature",
    # Оконная обработка сигналов
    "WindowConfig",
    "apply_window_function",
    "rolling_mean",
    "rolling_std",
    "rolling_max",
    "rolling_min",
    "compute_overlap",
    "split_into_windows",
    "merge_windows",
    "batch_rolling",
    # Статистические утилиты
    "StatsConfig",
    "describe",
    "zscore_array",
    "iqr",
    "winsorize",
    "percentile_rank",
    "outlier_mask",
    "running_stats",
    "weighted_mean",
    "weighted_std",
    "batch_describe",
    # Пороговая обработка
    "ThresholdConfig",
    "apply_threshold",
    "binarize",
    "adaptive_threshold",
    "soft_threshold",
    "threshold_score_matrix",
    "hysteresis_threshold",
    "otsu_threshold",
    "count_above",
    "fraction_above",
    "batch_threshold",
    # Интерполяция сигналов и оценок
    "InterpolationConfig",
    "lerp",
    "lerp_array",
    "bilinear_interpolate",
    "resample_1d",
    "fill_missing",
    "interpolate_scores",
    "smooth_interpolate",
    "batch_resample",
    # Случайная выборка для оптимизации
    "SamplingConfig",
    "uniform_sample",
    "sample_angle",
    "sample_position",
    "sample_positions_grid",
    "sample_permutation",
    "weighted_sample",
    "acceptance_probability",
    "sample_swap_pair",
    "batch_uniform_sample",
    # Оценка совместимости краёв
    "EdgeScoreConfig",
    "EdgeScoreResult",
    "score_edge_overlap",
    "score_edge_curvature",
    "score_edge_length",
    "score_edge_endpoints",
    "aggregate_edge_scores",
    "rank_edge_pairs",
    "batch_score_edges",
    # Температурные расписания для SA
    "ScheduleConfig",
    "TemperatureRecord",
    "linear_schedule",
    "geometric_schedule",
    "exponential_schedule",
    "cosine_schedule",
    "stepped_schedule",
    "get_temperature",
    "estimate_steps",
    "batch_temperatures",
    # Утилиты поворота изображений и точек
    "RotationConfig",
    "rotate_image_angle",
    "rotate_points_angle",
    "normalize_angle",
    "angle_difference",
    "nearest_discrete",
    "angles_to_matrix",
    "batch_rotate_images",
    "estimate_rotation",
    # Статистика фрагментов
    "FragmentMetrics",
    "CollectionStats",
    "compute_fragment_metrics",
    "compute_collection_stats",
    "area_histogram",
    "compare_collections",
    "outlier_indices",
    # Пространственный индекс
    "SpatialConfig",
    "SpatialEntry",
    "SpatialIndex",
    "build_spatial_index",
    "query_radius",
    "query_knn",
    "pairwise_distances",
    "cluster_by_distance",
    # Выравнивание и регистрация кривых
    "AlignmentConfig",
    "AlignmentResult",
    "normalize_for_alignment",
    "find_best_rotation",
    "find_best_translation",
    "compute_alignment_error",
    "align_curves_procrustes",
    "align_curves_icp",
    "alignment_score",
    "batch_align_curves",
    # Метрики сравнения кривых
    "CurveMetricConfig",
    "CurveComparisonResult",
    "curve_l2",
    "curve_l2_mirror",
    "hausdorff_distance",
    "frechet_distance_approx",
    "curve_length",
    "length_ratio",
    "compare_curves",
    "batch_compare_curves",
    # Анализ сегментов маски
    "SegmentConfig",
    "RegionInfo",
    "label_mask",
    "region_info",
    "all_regions",
    "filter_regions",
    "largest_region",
    "mask_from_labels",
    "mask_statistics",
    "mask_bounding_box",
    "extract_boundary",
    # Операции над полигонами
    "PolygonOpsConfig",
    "PolygonOverlapResult",
    "PolygonStats",
    "signed_area",
    "poly_ops_area",
    "poly_ops_perimeter",
    "poly_ops_centroid",
    "poly_ops_bbox",
    "polygon_stats",
    "poly_ops_point_in",
    "polygon_overlap",
    "remove_collinear",
    "ensure_ccw",
    "ensure_cw",
    "poly_ops_similarity",
    "batch_polygon_stats",
    "batch_polygon_overlap",
    # Утилиты матриц оценок
    "ScoreMatrixConfig",
    "MatrixStats",
    "RankEntry",
    "zero_diagonal",
    "symmetrize",
    "threshold_score_mat",
    "normalize_score_rows",
    "top_k_indices",
    "matrix_stats",
    "score_top_k_per_row",
    "filter_by_threshold",
    "intra_fragment_mask",
    "apply_intra_fragment_mask",
    "batch_matrix_stats",
    # Геометрические преобразования изображений
    "ImageTransformConfig",
    "TransformResult",
    "img_rotate",
    "flip_horizontal",
    "flip_vertical",
    "pad_image",
    "crop_img",
    "resize_image",
    "resize_to_max_side",
    "apply_affine_transform",
    "rotation_matrix_2x3",
    "batch_rotate_images_v2",
    "batch_pad",
    "batch_resize_to_max",
    # Фильтрация фрагментов
    "FragmentFilterConfig",
    "FragmentQuality",
    "compute_fragment_area",
    "compute_aspect_ratio",
    "compute_fill_ratio",
    "evaluate_fragment",
    "deduplicate_fragments",
    "filter_fragments",
    "sort_by_area",
    "top_k_fragments",
    "fragment_quality_summary",
    # Утилиты конфигурации
    "validate_section",
    "validate_range",
    "merge_dicts",
    "flatten_dict",
    "unflatten_dict",
    "overrides_from_env",
    "ConfigProfile",
    "PROFILES",
    "apply_profile",
    "list_profiles",
    "load_json_config",
    "save_json_config",
    "diff_configs",
    # Утилиты ICP-выравнивания
    "ICPConfig",
    "centroid",
    "center_points",
    "scale_points",
    "resample_uniform",
    "nearest_neighbours",
    "filter_correspondences",
    "svd_rotation",
    "svd_translation",
    "compute_rmse",
    "rmse_after_transform",
    "has_converged",
    "compose_transforms",
    "invert_transform",
    "PairAlignResult",
    "batch_nearest_neighbours",
    "transform_points",
    "align_to_first",
    # Утилиты дескрипторов
    "DescriptorConfig",
    "desc_l2_normalize",
    "desc_l1_normalize",
    "desc_batch_l2_normalize",
    "l2_distance",
    "cosine_distance",
    "chi2_distance",
    "l1_distance",
    "desc_distance",
    "pairwise_l2",
    "pairwise_cosine",
    "DescriptorMatch",
    "nn_match",
    "ratio_test",
    "mean_pool",
    "max_pool",
    "vlad_encode",
    "batch_nn_match",
    "top_k_matches",
    "filter_desc_matches",
    # Рендеринг
    "CanvasConfig",
    "MosaicConfig",
    "render_rotation_matrix_2d",
    "bounding_box_of_rotated",
    "compute_canvas_size",
    "make_blank_canvas",
    "resize_keep_aspect",
    "pad_to_square",
    "make_thumbnail",
    "render_paste_with_mask",
    "compute_grid_layout",
    "make_mosaic",
    "render_save_image",
    "horizontal_concat",
    # Трекер итераций
    "TrackerConfig",
    "StepRecord",
    "IterTracker",
    "create_iter_tracker",
    "record_step",
    "get_values",
    "get_steps",
    "get_best_record",
    "get_worst_record",
    "compute_delta",
    "is_improving",
    "find_plateau_start",
    "smooth_values",
    "tracker_stats",
    "compare_trackers",
    "merge_trackers",
    "window_stats",
    "top_k_records",
    # Профили контуров
    "ProfileConfig",
    "ProfileMatchResult",
    "sample_profile_along_contour",
    "contour_curvature",
    "smooth_profile",
    "normalize_profile_values",
    "profile_l2_distance",
    "profile_cosine_similarity",
    "best_cyclic_offset",
    "align_profiles",
    "match_profiles",
    "batch_match_profiles",
    "top_k_profile_matches",
    # Метрики размещения фрагментов
    "PlacementMetricsConfig",
    "PlacementMetrics",
    "placement_density",
    "bbox_of_contour",
    "bbox_area",
    "bbox_intersection_area",
    "compute_coverage",
    "compute_pairwise_overlap",
    "placement_quality_score",
    "assess_placement",
    "compare_placement_metrics",
    "best_placement_of",
    "normalize_placement_metrics",
    "batch_placement_quality_scores",
    # Оценка регионов маски
    "RegionScoreConfig",
    "RegionScore",
    "region_compactness",
    "region_extent",
    "mask_perimeter",
    "score_region",
    "evaluate_region",
    "filter_regions_by_score",
    "rank_regions",
    "top_k_regions",
    "region_score_stats",
    "batch_evaluate_regions",
    "normalize_region_scores",
    # Профили краёв фрагментов
    "EdgeProfileConfig",
    "EdgeProfile",
    "build_edge_profile",
    "profile_l2_distance",
    "profile_cosine_similarity",
    "profile_correlation",
    "resample_profile",
    "flip_profile",
    "mean_profile",
    "batch_build_profiles",
    "pairwise_l2_matrix",
    "best_matching_profile",
    # Оценки качества результатов поворота
    "RotationScoreConfig",
    "RotationScoreEntry",
    "make_rotation_entry",
    "filter_rotations_by_confidence",
    "filter_rotations_by_method",
    "filter_by_angle_range",
    "rank_rotations_by_confidence",
    "best_rotation_entry",
    "aggregate_angles",
    "rotation_score_stats",
    "angle_agreement",
    "batch_make_rotation_entries",
    "top_k_rotation_entries",
    "group_rotations_by_method",
    # Оценки и анализ перекрытий фрагментов
    "OverlapScoreConfig",
    "OverlapScoreEntry",
    "OverlapSummary",
    "make_overlap_entry",
    "summarise_overlaps",
    "filter_significant_overlaps",
    "filter_overlaps_by_area",
    "top_k_overlaps",
    "overlap_stats",
    "penalty_score",
    "batch_make_overlap_entries",
    "group_by_fragment",
    # Оценки размещения фрагментов
    "PlacementScoreConfig",
    "PlacementScoreEntry",
    "PlacementSummary",
    "make_placement_entry",
    "entries_from_history",
    "summarise_placement",
    "filter_positive_steps",
    "filter_placements_by_min_score",
    "top_k_steps",
    "rank_fragments",
    "placement_score_stats",
    "compare_placements",
    "batch_summarise_placements",
    # Оценки качества результатов отжига
    "AnnealingScoreConfig",
    "AnnealingScoreEntry",
    "AnnealingSummary",
    "make_annealing_entry",
    "entries_from_log",
    "summarise_annealing",
    "filter_accepted",
    "filter_rejected",
    "filter_annealing_by_min_score",
    "filter_by_temperature_range",
    "top_k_annealing_entries",
    "annealing_score_stats",
    "best_annealing_entry",
    "compare_summaries",
    "batch_summarise_annealing",
    # Оценки качества консенсуса
    "ConsensusScoreConfig",
    "ConsensusScoreEntry",
    "ConsensusSummary",
    "make_consensus_entry",
    "entries_from_votes",
    "summarise_consensus",
    "filter_consensus_pairs",
    "filter_non_consensus",
    "filter_by_vote_fraction",
    "top_k_consensus_entries",
    "consensus_score_stats",
    "agreement_score",
    "compare_consensus",
    "batch_summarise_consensus",
    # Оценки качества фрагментов и изображений
    "QualityScoreConfig",
    "QualityScoreEntry",
    "QualitySummary",
    "make_quality_entry",
    "entries_from_quality_reports",
    "summarise_quality",
    "filter_quality_acceptable",
    "filter_quality_rejected",
    "filter_by_overall",
    "filter_by_blur",
    "top_k_quality_entries",
    "quality_score_stats",
    "compare_quality",
    "batch_summarise_quality",
    # Ранжирование и фильтрация кандидатных пар
    "CandidateRankConfig",
    "CandidateRankEntry",
    "CandidateRankSummary",
    "make_candidate_entry",
    "entries_from_candidate_pairs",
    "summarise_rankings",
    "filter_selected_candidates",
    "filter_rejected_candidates",
    "filter_by_score_range",
    "filter_by_rank",
    "top_k_candidate_entries",
    "candidate_rank_stats",
    "compare_rankings",
    "batch_summarise_rankings",
    # Конвейерная фильтрация кандидатных пар
    "FilterStepConfig",
    "FilterStepResult",
    "FilterPipelineSummary",
    "make_filter_step",
    "steps_from_log",
    "summarise_pipeline",
    "filter_effective_steps",
    "filter_by_removal_rate",
    "most_aggressive_step",
    "least_aggressive_step",
    "pipeline_stats",
    "compare_pipelines",
    "batch_summarise_pipelines",
    # Нормализация и калибровка оценок
    "ScoreNormConfig",
    "ScoreNormEntry",
    "ScoreNormSummary",
    "make_norm_entry",
    "entries_from_scores",
    "summarise_norm",
    "filter_by_normalized_range",
    "filter_by_original_range",
    "top_k_norm_entries",
    "norm_entry_stats",
    "compare_norm_summaries",
    "batch_summarise_norm",
    # Анализ и ранжирование сопоставления форм
    "ShapeMatchConfig",
    "ShapeMatchEntry",
    "ShapeMatchSummary",
    "make_match_entry",
    "entries_from_match_results",
    "summarise_matches",
    "filter_good_matches",
    "filter_poor_matches",
    "filter_by_hu_dist",
    "filter_match_by_score_range",
    "top_k_match_entries",
    "match_entry_stats",
    "compare_match_summaries",
    "batch_summarise_matches",
    # Планирование и анализ сборки холста
    "CanvasBuildConfig",
    "PlacementEntry",
    "CanvasBuildSummary",
    "make_placement_entry",
    "entries_from_placements",
    "summarise_canvas_build",
    "filter_by_area",
    "filter_by_coverage_contribution",
    "top_k_by_coverage",
    "canvas_build_stats",
    "compare_canvas_summaries",
    "batch_summarise_canvas_builds",
    # Анализ и ранжирование результатов сборки пазла
    "AssemblyScoreConfig",
    "AssemblyScoreEntry",
    "AssemblySummary",
    "make_assembly_entry",
    "entries_from_assemblies",
    "summarise_assemblies",
    "filter_good_assemblies",
    "filter_poor_assemblies",
    "filter_assemblies_by_method",
    "filter_assemblies_by_score_range",
    "filter_by_min_fragments",
    "top_k_assembly_entries",
    "best_assembly_entry",
    "assembly_score_stats",
    "compare_assembly_summaries",
    "batch_summarise_assemblies",
    # Анализ и ранжирование сопоставления патчей
    "PatchScoreConfig",
    "PatchScoreEntry",
    "PatchScoreSummary",
    "make_patch_entry",
    "entries_from_patch_matches",
    "summarise_patch_scores",
    "filter_good_patch_scores",
    "filter_poor_patch_scores",
    "filter_patch_by_score_range",
    "filter_by_side_pair",
    "filter_by_ncc_range",
    "top_k_patch_entries",
    "best_patch_entry",
    "patch_score_stats",
    "compare_patch_summaries",
    "batch_summarise_patch_scores",
]
