"""
Утилиты: логирование, геометрия, кэш дескрипторов, ввод-вывод.

Модули:
    logger     — структурированное логирование с цветами (get_logger, stage, PipelineTimer)
    geometry   — геометрические операции (rotation_matrix_2d, polygon_area, poly_iou, …)
    cache      — LRU-кэш и дисковый кэш дескрипторов (DescriptorCache, DiskCache, @cached)
    io         — загрузка/сохранение фрагментов и Assembly (load_image_dir, save_assembly_json, …)
    profiler   — профилировщик шагов пайплайна (StepProfile, PipelineProfiler, @timed)
    visualizer — утилиты визуализации (word boxes, contours, matches, confidence bar)
    metrics    — метрики качества восстановления (ReconstructionMetrics, IoU, Kendall τ,
                 permutation distance, precision/recall, placement accuracy)
    image_stats    — статистический анализ изображений (ImageStats, энтропия, резкость,
                     гистограммные моменты, градиентные статистики, compare_images)
    patch_extractor — извлечение патчей (Patch, PatchSet, grid, sliding, random, border)
    image_io        — загрузка/сохранение (ImageRecord, load_image, save_image,
                      load_directory, filter_by_extension, parse_fragment_id,
                      resize_to_max, batch_resize)
    transform_utils — геометрические преобразования (rotate, flip, scale, crop_region,
                      affine_from_params, compose_affines, apply_affine,
                      apply_homography, batch_rotate)
    color_utils     — цветовые утилиты (to_gray, to_lab, to_hsv, from_lab,
                      compute_histogram, compare_histograms, dominant_colors,
                      color_distance, strip_histogram)
    mask_utils      — утилиты масок (create_alpha_mask, apply_mask, erode_mask,
                      dilate_mask, mask_from_contour, combine_masks,
                      crop_to_mask, invert_mask)
    array_utils     — утилиты numpy-массивов (normalize_array, pad_to_shape,
                      crop_center, stack_arrays, chunk_array, sliding_window,
                      flatten_images, unflatten_images, compute_pairwise_norms)
    contour_utils   — утилиты контуров (simplify_contour, interpolate_contour,
                      contour_area, contour_perimeter, contour_bbox,
                      contour_centroid, contour_iou, align_contour_orientation,
                      contours_to_mask, mask_to_contour)
    histogram_utils — утилиты гистограмм (compute_1d_histogram, compute_2d_histogram,
                      histogram_equalization, histogram_specification,
                      earth_mover_distance, chi_squared_distance,
                      histogram_intersection, backproject, joint_histogram)
    keypoint_utils  — ключевые точки и дескрипторы (KeypointSet, detect_keypoints,
                      filter_by_response, filter_by_region, describe_keypoints,
                      match_descriptors, filter_matches_ransac, keypoints_to_array,
                      array_to_keypoints, compute_match_score)
    signal_utils    — 1D обработка сигналов (smooth_signal, normalize_signal,
                      find_peaks, find_valleys, compute_autocorrelation,
                      compute_cross_correlation, signal_energy, segment_signal,
                      resample_signal, phase_shift)
    bbox_utils      — утилиты ограничивающих прямоугольников (BBox, bbox_iou,
                      bbox_intersection, bbox_union, expand_bbox, crop_image,
                      bboxes_from_mask, merge_overlapping_bboxes,
                      bbox_center, bbox_aspect_ratio)
    sparse_utils    — утилиты разреженных матриц оценок (SparseEntry,
                      to_sparse_entries, from_sparse_entries, sparse_top_k,
                      threshold_matrix, symmetrize_matrix, normalize_matrix,
                      diagonal_zeros, matrix_sparsity, top_k_per_row)
    clustering_utils — кластеризация фрагментов (ClusterResult, kmeans_cluster,
                       assign_to_clusters, compute_inertia, silhouette_score_approx,
                       hierarchical_cluster, find_optimal_k, cluster_indices,
                       merge_clusters)
    distance_utils  — метрики расстояния и сходства (euclidean_distance,
                      cosine_distance, cosine_similarity, manhattan_distance,
                      chebyshev_distance, hausdorff_distance, chamfer_distance,
                      normalized_distance, pairwise_distances, nearest_neighbor_dist)
    smoothing_utils — сглаживание сигналов и контуров (SmoothingParams,
                      moving_average, gaussian_smooth, median_smooth,
                      exponential_smooth, savgol_smooth, smooth_contour,
                      apply_smoothing, batch_smooth)
"""
from .logger import (
    get_logger,
    stage,
    ProgressBar,
    PipelineTimer,
    log,
)
from .geometry import (
    rotation_matrix_2d,
    rotate_points,
    polygon_area,
    polygon_centroid,
    bbox_from_points,
    resample_curve,
    align_centroids,
    poly_iou,
    point_in_polygon,
    normalize_contour,
    smooth_contour,
    curvature,
)
from .cache import (
    DescriptorCache,
    DiskCache,
    descriptor_key,
    cached,
    get_default_cache,
    clear_default_cache,
)
from .io import (
    load_image_dir,
    fragments_from_images,
    save_assembly_json,
    load_assembly_json,
    save_fragments_npz,
    load_fragments_npz,
    FragmentSetInfo,
)
from .profiler import (
    StepProfile,
    PipelineProfiler,
    profile_function,
    timed,
    format_duration,
    compare_profilers,
)
from .visualizer import (
    VisConfig,
    draw_word_boxes,
    draw_fragment_boxes,
    draw_edge_matches,
    draw_contour,
    draw_assembly_layout,
    draw_skew_angle,
    draw_confidence_bar,
    tile_images,
)
from .metrics import (
    ReconstructionMetrics as AssemblyReconstructionMetrics,
    placement_iou,
    order_kendall_tau,
    permutation_distance,
    assembly_precision_recall,
    fragment_placement_accuracy,
    compute_reconstruction_metrics,
)
from .image_stats import (
    ImageStats,
    compute_entropy,
    compute_sharpness,
    compute_histogram_stats,
    compute_gradient_stats,
    compute_image_stats,
    compare_images,
    batch_stats,
)
from .patch_extractor import (
    Patch,
    PatchSet,
    extract_grid_patches,
    extract_sliding_patches,
    extract_random_patches,
    extract_border_patches,
    filter_patches,
    batch_extract_patches,
)
from .image_io import (
    ImageRecord,
    load_image,
    save_image,
    load_directory,
    filter_by_extension,
    parse_fragment_id,
    resize_to_max,
    batch_resize,
)
from .transform_utils import (
    rotate_image,
    flip_image,
    scale_image,
    crop_region,
    affine_from_params,
    compose_affines,
    apply_affine,
    apply_homography,
    batch_rotate,
)
from .color_utils import (
    to_gray,
    to_lab,
    to_hsv,
    from_lab,
    compute_histogram,
    compare_histograms,
    dominant_colors,
    color_distance,
    strip_histogram,
)
from .mask_utils import (
    create_alpha_mask,
    apply_mask,
    erode_mask,
    dilate_mask,
    mask_from_contour,
    combine_masks,
    crop_to_mask,
    invert_mask,
)
from .array_utils import (
    normalize_array,
    pad_to_shape,
    crop_center,
    stack_arrays,
    chunk_array,
    sliding_window,
    flatten_images,
    unflatten_images,
    compute_pairwise_norms,
)
from .contour_utils import (
    simplify_contour,
    interpolate_contour,
    contour_area,
    contour_perimeter,
    contour_bbox,
    contour_centroid,
    contour_iou,
    align_contour_orientation,
    contours_to_mask,
    mask_to_contour,
)
from .histogram_utils import (
    compute_1d_histogram,
    compute_2d_histogram,
    histogram_equalization,
    histogram_specification,
    earth_mover_distance,
    chi_squared_distance,
    histogram_intersection,
    backproject,
    joint_histogram,
)
from .keypoint_utils import (
    KeypointSet,
    detect_keypoints,
    filter_by_response,
    filter_by_region,
    describe_keypoints,
    match_descriptors,
    filter_matches_ransac,
    keypoints_to_array,
    array_to_keypoints,
    compute_match_score,
)
from .signal_utils import (
    smooth_signal,
    normalize_signal,
    find_peaks,
    find_valleys,
    compute_autocorrelation,
    compute_cross_correlation,
    signal_energy,
    segment_signal,
    resample_signal,
    phase_shift,
)
from .bbox_utils import (
    BBox,
    bbox_iou,
    bbox_intersection,
    bbox_union,
    expand_bbox,
    crop_image,
    bboxes_from_mask,
    merge_overlapping_bboxes,
    bbox_center,
    bbox_aspect_ratio,
)
from .sparse_utils import (
    SparseEntry,
    to_sparse_entries,
    from_sparse_entries,
    sparse_top_k,
    threshold_matrix,
    symmetrize_matrix,
    normalize_matrix,
    diagonal_zeros,
    matrix_sparsity,
    top_k_per_row,
)
from .clustering_utils import (
    ClusterResult,
    kmeans_cluster,
    assign_to_clusters,
    compute_inertia,
    silhouette_score_approx,
    hierarchical_cluster,
    find_optimal_k,
    cluster_indices,
    merge_clusters,
)
from .distance_utils import (
    euclidean_distance,
    cosine_distance,
    cosine_similarity,
    manhattan_distance,
    chebyshev_distance,
    hausdorff_distance,
    chamfer_distance,
    normalized_distance,
    pairwise_distances,
    nearest_neighbor_dist,
)
from .smoothing_utils import (
    SmoothingParams,
    moving_average,
    gaussian_smooth,
    median_smooth,
    exponential_smooth,
    savgol_smooth,
    smooth_contour as smooth_contour_signal,
    apply_smoothing,
    batch_smooth,
)

__all__ = [
    # Логирование
    "get_logger",
    "stage",
    "ProgressBar",
    "PipelineTimer",
    "log",
    # Геометрия
    "rotation_matrix_2d",
    "rotate_points",
    "polygon_area",
    "polygon_centroid",
    "bbox_from_points",
    "resample_curve",
    "align_centroids",
    "poly_iou",
    "point_in_polygon",
    "normalize_contour",
    "smooth_contour",
    "curvature",
    # Кэш
    "DescriptorCache",
    "DiskCache",
    "descriptor_key",
    "cached",
    "get_default_cache",
    "clear_default_cache",
    # Ввод-вывод
    "load_image_dir",
    "fragments_from_images",
    "save_assembly_json",
    "load_assembly_json",
    "save_fragments_npz",
    "load_fragments_npz",
    "FragmentSetInfo",
    # Профилировщик
    "StepProfile",
    "PipelineProfiler",
    "profile_function",
    "timed",
    "format_duration",
    "compare_profilers",
    # Визуализация
    "VisConfig",
    "draw_word_boxes",
    "draw_fragment_boxes",
    "draw_edge_matches",
    "draw_contour",
    "draw_assembly_layout",
    "draw_skew_angle",
    "draw_confidence_bar",
    "tile_images",
    # Метрики качества
    "AssemblyReconstructionMetrics",
    "placement_iou",
    "order_kendall_tau",
    "permutation_distance",
    "assembly_precision_recall",
    "fragment_placement_accuracy",
    "compute_reconstruction_metrics",
    # Статистический анализ изображений
    "ImageStats",
    "compute_entropy",
    "compute_sharpness",
    "compute_histogram_stats",
    "compute_gradient_stats",
    "compute_image_stats",
    "compare_images",
    "batch_stats",
    # Извлечение патчей
    "Patch",
    "PatchSet",
    "extract_grid_patches",
    "extract_sliding_patches",
    "extract_random_patches",
    "extract_border_patches",
    "filter_patches",
    "batch_extract_patches",
    # Ввод-вывод изображений
    "ImageRecord",
    "load_image",
    "save_image",
    "load_directory",
    "filter_by_extension",
    "parse_fragment_id",
    "resize_to_max",
    "batch_resize",
    # Геометрические преобразования
    "rotate_image",
    "flip_image",
    "scale_image",
    "crop_region",
    "affine_from_params",
    "compose_affines",
    "apply_affine",
    "apply_homography",
    "batch_rotate",
    # Цветовые утилиты
    "to_gray",
    "to_lab",
    "to_hsv",
    "from_lab",
    "compute_histogram",
    "compare_histograms",
    "dominant_colors",
    "color_distance",
    "strip_histogram",
    # Утилиты масок
    "create_alpha_mask",
    "apply_mask",
    "erode_mask",
    "dilate_mask",
    "mask_from_contour",
    "combine_masks",
    "crop_to_mask",
    "invert_mask",
    # Утилиты numpy-массивов
    "normalize_array",
    "pad_to_shape",
    "crop_center",
    "stack_arrays",
    "chunk_array",
    "sliding_window",
    "flatten_images",
    "unflatten_images",
    "compute_pairwise_norms",
    # Утилиты контуров
    "simplify_contour",
    "interpolate_contour",
    "contour_area",
    "contour_perimeter",
    "contour_bbox",
    "contour_centroid",
    "contour_iou",
    "align_contour_orientation",
    "contours_to_mask",
    "mask_to_contour",
    # Утилиты гистограмм
    "compute_1d_histogram",
    "compute_2d_histogram",
    "histogram_equalization",
    "histogram_specification",
    "earth_mover_distance",
    "chi_squared_distance",
    "histogram_intersection",
    "backproject",
    "joint_histogram",
    # Утилиты ключевых точек
    "KeypointSet",
    "detect_keypoints",
    "filter_by_response",
    "filter_by_region",
    "describe_keypoints",
    "match_descriptors",
    "filter_matches_ransac",
    "keypoints_to_array",
    "array_to_keypoints",
    "compute_match_score",
    # 1D обработка сигналов
    "smooth_signal",
    "normalize_signal",
    "find_peaks",
    "find_valleys",
    "compute_autocorrelation",
    "compute_cross_correlation",
    "signal_energy",
    "segment_signal",
    "resample_signal",
    "phase_shift",
    # Утилиты ограничивающих прямоугольников
    "BBox",
    "bbox_iou",
    "bbox_intersection",
    "bbox_union",
    "expand_bbox",
    "crop_image",
    "bboxes_from_mask",
    "merge_overlapping_bboxes",
    "bbox_center",
    "bbox_aspect_ratio",
    # Утилиты разреженных матриц оценок
    "SparseEntry",
    "to_sparse_entries",
    "from_sparse_entries",
    "sparse_top_k",
    "threshold_matrix",
    "symmetrize_matrix",
    "normalize_matrix",
    "diagonal_zeros",
    "matrix_sparsity",
    "top_k_per_row",
    # Кластеризация фрагментов
    "ClusterResult",
    "kmeans_cluster",
    "assign_to_clusters",
    "compute_inertia",
    "silhouette_score_approx",
    "hierarchical_cluster",
    "find_optimal_k",
    "cluster_indices",
    "merge_clusters",
    # Метрики расстояния и сходства
    "euclidean_distance",
    "cosine_distance",
    "cosine_similarity",
    "manhattan_distance",
    "chebyshev_distance",
    "hausdorff_distance",
    "chamfer_distance",
    "normalized_distance",
    "pairwise_distances",
    "nearest_neighbor_dist",
    # Сглаживание сигналов и контуров
    "SmoothingParams",
    "moving_average",
    "gaussian_smooth",
    "median_smooth",
    "exponential_smooth",
    "savgol_smooth",
    "smooth_contour_signal",
    "apply_smoothing",
    "batch_smooth",
]
