"""Модули оценки качества сборки пазла.

Доступные модули:
    consistency_checker — проверка согласованности сборки (ConsistencyIssue,
                          ConsistencyReport, check_unique_ids, check_all_present,
                          check_canvas_bounds, check_score_threshold,
                          check_gap_uniformity, run_consistency_check,
                          batch_consistency_check)
    boundary_scorer     — оценка совместимости по граничным пикселям (BoundarySide,
                          BoundaryScore, ScoringConfig, intensity_compatibility,
                          gradient_compatibility, color_compatibility,
                          score_boundary, score_matrix, batch_score_boundaries)
    global_ranker       — глобальное ранжирование фрагментов (RankedPair, RankingConfig,
                          normalize_matrix, aggregate_score_matrices, rank_pairs,
                          top_k_candidates, global_rank, score_vector, batch_global_rank)
    pair_filter         — фильтрация кандидатных пар (FilterConfig, CandidatePair,
                          FilterReport, filter_by_score, filter_by_inlier_count,
                          filter_top_k, deduplicate_pairs, filter_top_k_per_fragment,
                          filter_pairs, merge_filter_results, batch_filter)
    score_normalizer    — нормализация матриц оценок (NormMethod, NormalizedMatrix,
                          minmax_normalize_matrix, zscore_normalize_matrix,
                          rank_normalize_matrix, softmax_normalize_matrix,
                          sigmoid_normalize_matrix, normalize_score_matrix,
                          combine_score_matrices, batch_normalize_matrices)
    match_evaluator     — оценка качества сопоставления пар (EvalConfig, MatchEval,
                          EvalReport, compute_precision, compute_recall,
                          compute_f_score, evaluate_match, evaluate_batch_matches,
                          aggregate_eval, filter_by_score, rank_matches)
    threshold_selector  — выбор порога бинаризации оценок (ThresholdConfig,
                          ThresholdResult, select_fixed_threshold,
                          select_percentile_threshold, select_otsu_threshold,
                          select_f1_threshold, select_adaptive_threshold,
                          select_threshold, apply_threshold, batch_select_thresholds)
    pair_ranker         — ранжирование пар фрагментов (RankConfig, RankerPair,
                          RankResult, compute_pair_score, rank_fragment_pairs,
                          build_rank_matrix, merge_rank_results)
"""
from .consistency_checker import (
    ConsistencyIssue,
    ConsistencyReport,
    check_unique_ids,
    check_all_present,
    check_canvas_bounds,
    check_score_threshold,
    check_gap_uniformity,
    run_consistency_check,
    batch_consistency_check,
)
from .boundary_scorer import (
    BoundarySide,
    BoundaryScore,
    ScoringConfig,
    intensity_compatibility,
    gradient_compatibility,
    color_compatibility,
    score_boundary,
    score_matrix,
    batch_score_boundaries,
)
from .global_ranker import (
    RankedPair,
    RankingConfig,
    normalize_matrix,
    aggregate_score_matrices,
    rank_pairs,
    top_k_candidates,
    global_rank,
    score_vector,
    batch_global_rank,
)
from .pair_filter import (
    FilterConfig,
    CandidatePair,
    FilterReport,
    filter_by_score,
    filter_by_inlier_count,
    filter_top_k,
    deduplicate_pairs,
    filter_top_k_per_fragment,
    filter_pairs,
    merge_filter_results,
    batch_filter as batch_filter_pairs,
)
from .score_normalizer import (
    NormMethod,
    NormalizedMatrix,
    minmax_normalize_matrix,
    zscore_normalize_matrix,
    rank_normalize_matrix,
    softmax_normalize_matrix,
    sigmoid_normalize_matrix,
    normalize_score_matrix,
    combine_score_matrices,
    batch_normalize_matrices,
)
from .match_evaluator import (
    EvalConfig,
    MatchEval,
    EvalReport,
    compute_precision,
    compute_recall,
    compute_f_score,
    evaluate_match,
    evaluate_batch_matches,
    aggregate_eval,
    filter_by_score as filter_evals_by_score,
    rank_matches,
)
from .threshold_selector import (
    ThresholdConfig,
    ThresholdResult,
    select_fixed_threshold,
    select_percentile_threshold,
    select_otsu_threshold,
    select_f1_threshold,
    select_adaptive_threshold,
    select_threshold,
    apply_threshold,
    batch_select_thresholds,
)
from .pair_ranker import (
    RankConfig,
    RankedPair as RankerPair,
    RankResult,
    compute_pair_score,
    rank_pairs as rank_fragment_pairs,
    build_rank_matrix,
    merge_rank_results,
)

__all__ = [
    # Проверка согласованности
    "ConsistencyIssue",
    "ConsistencyReport",
    "check_unique_ids",
    "check_all_present",
    "check_canvas_bounds",
    "check_score_threshold",
    "check_gap_uniformity",
    "run_consistency_check",
    "batch_consistency_check",
    # Оценка граничной совместимости
    "BoundarySide",
    "BoundaryScore",
    "ScoringConfig",
    "intensity_compatibility",
    "gradient_compatibility",
    "color_compatibility",
    "score_boundary",
    "score_matrix",
    "batch_score_boundaries",
    # Глобальное ранжирование
    "RankedPair",
    "RankingConfig",
    "normalize_matrix",
    "aggregate_score_matrices",
    "rank_pairs",
    "top_k_candidates",
    "global_rank",
    "score_vector",
    "batch_global_rank",
    # Фильтрация кандидатных пар
    "FilterConfig",
    "CandidatePair",
    "FilterReport",
    "filter_by_score",
    "filter_by_inlier_count",
    "filter_top_k",
    "deduplicate_pairs",
    "filter_top_k_per_fragment",
    "filter_pairs",
    "merge_filter_results",
    "batch_filter_pairs",
    # Нормализация матриц оценок
    "NormMethod",
    "NormalizedMatrix",
    "minmax_normalize_matrix",
    "zscore_normalize_matrix",
    "rank_normalize_matrix",
    "softmax_normalize_matrix",
    "sigmoid_normalize_matrix",
    "normalize_score_matrix",
    "combine_score_matrices",
    "batch_normalize_matrices",
    # Оценка качества сопоставления
    "EvalConfig",
    "MatchEval",
    "EvalReport",
    "compute_precision",
    "compute_recall",
    "compute_f_score",
    "evaluate_match",
    "evaluate_batch_matches",
    "aggregate_eval",
    "filter_evals_by_score",
    "rank_matches",
    # Выбор порога бинаризации оценок
    "ThresholdConfig",
    "ThresholdResult",
    "select_fixed_threshold",
    "select_percentile_threshold",
    "select_otsu_threshold",
    "select_f1_threshold",
    "select_adaptive_threshold",
    "select_threshold",
    "apply_threshold",
    "batch_select_thresholds",
    # Ранжирование пар фрагментов
    "RankConfig",
    "RankerPair",
    "RankResult",
    "compute_pair_score",
    "rank_fragment_pairs",
    "build_rank_matrix",
    "merge_rank_results",
]
